kiwicom/margarita

.eslintrc.js
this rule is stil applied through prettier. vscode eslint autofix is confused
when this rule is applied multiple times. It adds extra commas and they have to be
manually removed after
=> Eslint disable comma-dangle rule from eslint and flow

packages/components/index.js, packages/components/src/AdaptableBadge/AdaptableBadge.js, packages/components/src/AdaptableBadge/README.md, packages/components/src/AdaptableBadge/index.js, packages/components/src/SearchParamsSummary/SearchParamsSummary.js, packages/components/src/SearchParamsSummary/SearchParamsSummary.stories.js, packages/components/src/SearchParamsSummary/__tests__/index.test.js, packages/components/src/SearchParamsSummary/index.js
Summary: AdaptableBadge had to be added for this move to be possible; this is just a temporary fix and should eventually live inside @kiwicom/universal-components (it's very similar to current implementation of FilterButton there for instance, so refactor is necessary).
I left the stories file for posterity; we might want to add some Storybook-like capacity to the component library specific to margarita.
=> Feat: Adding SearchParamsSummary component

flow-typed/npm/react-native-web_vx.x.x.js, packages/components/index.js, packages/components/src/ConnectionCard/BadgesContainer.js, packages/components/src/ConnectionCard/ConnectionCard.js, packages/components/src/ConnectionCard/ConnectionCardRow.js, packages/components/src/ConnectionCard/TripSector.js, packages/components/src/ConnectionCard/__tests__/ConnectionCard.test.js, packages/components/src/ConnectionCard/index.js
Summary:
TODO Inquire why one of the tests for ConnectionCard fails in this environment and worked fine in @kiwicom/universal-components;
LocalizedPrice is not available in @kiwicom/universal-components@0.0.6
=> This must be revisited once we publish v0.0.8 of @kiwicom/universal-components
This is how it can be used:
```
const hasReturnConnection = true;
const hasBadges = true;
// const localizedPrice = '$455.3455';
return (
<ConnectionCard
wayForth={[
{
id: 1,
arrival: 'Berlin TXL',
arrivalTime: '14:20',
carrier: { code: 'OK', name: 'Czech Airlines' },
tripDate: 'Mon 22 Oct',
departure: 'Prague PRG',
departureTime: '13:20',
duration: '1h',
},
{
id: 2,
arrival: 'Moscow VKO',
arrivalTime: '20:20',
carrier: { code: 'FR', type: 'airline', name: 'Ryanair' },
tripDate: 'Mon 22 Oct',
departure: …
```
=> Feat: Added ConnectionCard component

.gitignore, apps/core/package.json, apps/core/scenes/search/Search.js, apps/web/next.config.js, apps/web/package.json, apps/web/pages/_document.js, packages/components/src/TimelineInformation/__tests__/__snapshots__/TimelineInformation.test.js.snap, packages/components/src/passengersInputs/PassengersInputs.js, packages/components/src/passengersInputs/__tests__/__snapshots__/PassengersInputs.test.js.snap, packages/components/src/select/Select.js, packages/components/src/select/SelectOption.js, packages/components/src/select/__tests__/__snapshots__/Select.test.js.snap, yarn.lock
Summary: I had to modify the webpack config for the Nextjs application to load the orbit-icons.ttf file. Basically, it copies the font files over to apps/web/static/fonts and they are then accessible; appending a style tag in _document.js makes the Icon component from '@kiwicom/universal-components' work without adding any CSS file.
I had to take into account some breaking changes for Button and RadioButton component: label prop is preferred if there is no need for styling; children prop is used for specific components and/or Text component with diffeerent styling.
=> Chore: Upgraded @kiwicom/universal-components to v0.0.8

.eslintrc.js, apps/graphql/package.json, apps/graphql/src/Schema.js, apps/graphql/src/dataloaders/Itinerariesloader.js, apps/graphql/src/dataloaders/Locationsloader.js, packages/components/src/ConnectionCard/__tests__/ConnectionCard.test.js, yarn.lock
Used OptimisticDataloader from @kiwicom/graphql-utils
Original data-loader kills load batch if one of this response values is
Error instance. This optimistic data-loader keeps Error value as a valid
response. This means that it's possible to return as many responses
as possible and convert Errors to the error messages in the response
if necessary.
@see https://github.com/facebook/dataloader/issues/41
=> Chore: update @kiwicom/graphql-utils to v0.3.0

apps/graphql/src/services/Fetch.js
Summary: Fetch is currently failing in master because of url change from `Logger` implementation.
Changed back to original value.
=> Fix: Changed fetch url

apps/core/scenes/search/Search.js, package.json, yarn.lock
Summary:
Added limits to `DatePicker` implementation in `Search` form. Smaller value than current day cannot be selected now. For `return` flights, `departure` cannot be bigger than `return` date.
Replaced `luxon` with `date-fns` in `Search` form.
Related to #118
=> Fix: Added search dates limits

.gitignore, apps/graphql/.babelrc, apps/graphql/index.js, apps/graphql/lambda/graphql.js, apps/graphql/package.json, apps/graphql/src/server.js, apps/graphql/src/services/TestingTools.js, apps/web/package.json, netlify.toml, package.json, yarn.lock
Summary: After this PR is merged, Netlify will build both apps whenever a change occurs on the master branch.
apps/graphql/lambda is the folder that will be built by Netlify; so right now, only graphql.js would be built. Once build is successful, the Netlify Function is available at /.netlify/functions/<name_of_file> if <name_of_file>.js is in apps/graphql/lambda.
It will also deploy the static site from NextJs, which is built into 'apps/web/out'.
Because we are using `react-native-dotenv` in @kiwicom/margarita-relay, we need to explicitly create a .env file from the environment variables (which are already added to Netlify Deploy Settings); hence the 'echo GRAPHQL_URL=$GRAPHQL_URL > .env;' inside netlify.toml. That means we will need to be mindful of when we use more environment …
=> Chore: Deployed Margarita's graphql and web apps on Netlify

.eslintignore, .gitignore, apps/graphql/lambda/graphql.js, apps/graphql/package.json, apps/graphql/serverless.yml, apps/graphql/webpack.config.js, netlify.toml, package.json, yarn.lock
Summary: Currently, the deployment process is manual. Adding it to CircleCI will be done in a separate PR.
I removed the function build and deploy on Netlify.
Assuming you have AWS credentials with aws-cli configured and that you are in apps/graphql, you would just need to do:
- `yarn webpack`: this builds the server into a Node-compatible JavaScript
- `serverless deploy function --function margarita-graphql`: this will update the Lambda function
We could probably add a test to make sure the deployment was successful, by sending a POST request to the endpoint for example. If it did not work, it should somehow rollback (though I am not sure how that works precisely)
=> Feat: Added serverless deployment config

.circleci/config.yml
"yarn install" can change the yarn.lock file, but we don't want this behavior in the CI
=> Chore: added --frozen-lockfile to yarn command in the CI

.circleci/config.yml, .gitignore, apps/graphql/package.json, package.json
Summary: Netlify functions were not enough for us, so CircleCI should now deploy our GraphQL server to AWS Lambda when we merge into master.
=> Chore: CircleCI autodeploys GraphQL server to AWS Lambda

apps/graphql/package.json, apps/graphql/webpack.config.js
Summary: Adding AllBookings.json somehow broke the GraphQL build and removing json-loader helped for the build to complete.
=> Fix: json-loader removed for GraphQL build to go smoothly

.eslintignore, apps/web/components/withPageRouter.js, apps/web/pages/results.js, packages/components/src/SearchParamsSummary/SearchParamsSummary.js
Summary: When going to /results page from a built nextjs application, getInitialProps and the likes are ignored. That meant that refreshing /results would return Error because the query params were not taken into account.
I used the solution from this comment https://github.com/zeit/next.js/issues/4804#issuecomment-451558569, and it works pretty well.
Caveat is that we show for a brief moment a sort of broken state. That should be improved.
=> Fix: (Partial) Hydrate props from query params

.circleci/config.yml
~* Summary: We are already running the test when reviewing the PR, so it is not necessary to re-run the test after we merged into `master`; we can go straight to `build-and-deploy-graphql`.~
=> Fix: CircleCI should run `build-and-deploy-graphql` after `test` is successful

apps/web/pages/_document.js
Summary: Added `-webkit-font-smoothing` to global styles to improve fonts rendering on macOS.
Before:
After (it's a subtle change visible mostly on bold and small text and font icons):
=> Feat: Improved font rendering

apps/core/package.json, packages/components/package.json, packages/components/src/TimelineInformation/__tests__/__snapshots__/TimelineInformation.test.js.snap, yarn.lock
Summary: `release-it` config was broken in @kiwicom/universal-components and v0.0.10 effectively shipped an old build... Some global exports were missing too.
=> Chore: Upgrading @kiwicom/universal-components v0.0.11

packages/utils/layoutContext/LayoutContext.js
Summary:
Fixing problem related to responsive layout and server-side rendering.
Layout value initialisation has to be moved from `LayoutContextProvider` constructor to prevent non-matching classes error on initial render.
=> Fix: Responsive web version

packages/utils/src/withContext/withContext.js
Summary: Extended `withContext` to handle elements with children prop. And prevent it to be overridden during `cloneElement`.
This update is necessary for future `LayoutContext` implementation inside `Layout` component to improve initial web rendering.
=> Feat: Updated withContext children prop handling

apps/mobile/index.js, packages/components/index.js, packages/components/src/SearchParamsSummary/SearchParamsSummary.js, packages/components/src/text/Text.js, packages/components/src/text/__tests__/Text.android.test.js, packages/components/src/text/__tests__/Text.ios.test.js, packages/components/src/text/__tests__/Text.web.test.js, packages/components/src/text/__tests__/__snapshots__/Text.android.test.js.snap, packages/components/src/text/__tests__/__snapshots__/Text.ios.test.js.snap
Summary: Loading fonts with Expo does not allow the use of `fontStyle` and `fontWeight`, this PR adds a new Text wrapper component to be used instead of @kiwicom/universal-components' Text which takes into account weight='bold' and italic props for iOS and Android.
Note: Once all components use this new Text component, we should add an eslint rule to prevent Text import from '@kiwicom/universal-components'.
=> Fix: New Text component wrapper for bold and italic to work on mobile

apps/web/components/Layout.js, apps/web/components/__tests__/Layout.test.js, apps/web/pages/_app.js
Summary: Moved `LayoutContextProvider` from `Layout` component to custom `App` in web version. 
To make context available in all sub-components.
Related to #231
=> Refactor: Moved LayoutContext to _app.js

packages/components/src/shareIcon/ShareIcon.js
Summary: This was breaking MenuItem component as cloning ShareIcon did not pass props to underlying icon component.
=> Fix: ShareIcon passes props to underlying Icon component

packages/components/src/PlaceCard/PlaceCard.js, packages/components/src/SearchParamsSummary/__tests__/index.test.js, packages/components/src/TimelineFlightDetail/components/AdditionalInfoCard.js, packages/components/src/TimelineFlightDetail/components/CardHeader.js, packages/components/src/TimelineInformation/TimelineCabinBaggage.js, packages/components/src/TimelineInformation/TimelineDate.js, packages/components/src/TimelineInformation/TimelineDifferentAirport.js, packages/components/src/TimelineInformation/TimelineInformation.js, packages/components/src/TimelineInformation/TimelinePriorityBoarding.js, packages/components/src/TimelineInformation/__tests__/TimelineInformation.test.js, packages/components/src/TimelineInformation/__tests__/__snapshots__/TimelineInformation.test.js.snap, packages/components/src/modal/__tests__/Modal.test.js, packages/components/src/passengersButton/PassengersButton.js, packages/components/src/passengersButton/PassengersButton.native.js, packages/components/src/passengersInputs/PassengersInputs.js, packages/components/src/passengersInputs/PassengersInputsLine.js, packages/components/src/select/SelectOption.js, packages/components/src/tripInput/TripInput.js, packages/components/src/tripTypeButton/TripTypeButton.js, packages/components/src/tripTypeSwitch/TripTypeSwitchOption.js
Summary: This is a follow up PR to https://github.com/kiwicom/margarita/pull/248; we should use this Text wrapper component to ensure that `fontWeight` bold and `fontStyle` italic get applied correctly on iOS and Android through Expo.
Note that we should use `weight='bold'` and `italic` props instead of passing them through `style` prop (unless we need the text to be bold only on `web` for example).
=> Chore: Use Text component wrapper in @kiwicom/margarita-components

.flowconfig
Summary: Added `max_workers` limit to flow configuration to prevent CircleCI consuming too many resources.
Found this solution after investigating CircleCI logs.
Where we have similar errors as mentioned in this issue https://github.com/flowtype/flow-bin/issues/138 with suggested solution.
=> Fix: Fixed failing flow on CircleCI

apps/core/scenes/search/Search.js, apps/web/components/Layout.js, apps/web/components/__tests__/Layout.test.js, packages/utils/layoutContext/LayoutContext.js
Summary: Website content is shown after `layout` value initialisation, to prevent ugly layout reshuffling during initial render.
**Note:** I've tried to show spinner during `layout` initialisation but it just blinked for a few milliseconds which doesn't really improved experience.
So I've decided to remove it and simply show nothing during short initialisation, which looks better at the end.
Closes #231
=> Feat: Improved initial web rendering

apps/core/scenes/search/SearchContext.js
I had a discussion with @JoseDuSV about adding some default values to search form for better development experience, in future I would like to change it to use the nearest location as it is on kiwi.com
=> Feat: add default values for the place picker

apps/web/package.json, package.json, yarn.lock
Summary: This package does not seem to be used at all in the repo; I tried `yarn dev` and `yarn mobile` without any problems, etc. Tests are passing, so no regression expected.
=> Chore: Remove schedule dependency

apps/graphql/src/dataloaders/ItinerariesloaderTypes.js, apps/graphql/src/dataloaders/__tests__/itinerariesHelpers.test.js, apps/graphql/src/dataloaders/bookingsLoader/BookingFlowTypes.js, apps/graphql/src/dataloaders/itinerariesHelpers.js, apps/graphql/src/datasets/Itineraries.json, apps/graphql/src/queries/__tests__/Itineraries.test.js, apps/graphql/src/queries/__tests__/__snapshots__/Itineraries.test.js.snap, apps/graphql/src/types/output/RouteStop.js, apps/graphql/src/types/output/Sector.js, apps/graphql/src/types/output/Segment.js, apps/graphql/src/types/output/Trip.js
This should make reuse on FE easier when time and location is on same object.
Next iterations: Use new structure on FE.
Replace Trip type on MMB graphql with Sector type.
=> Graphql: Add RouteStop type to Sector and Segment

.flowconfig, .jest.json, apps/core/components/ItineraryCard/ItineraryCardWrapper.web.js, apps/core/components/ItineraryCard/TimelineArrow.js, apps/core/components/ItineraryCard/Transporters.js, apps/core/package.json, apps/core/scenes/bookingDetail/menuGroups/Manage.js, apps/core/scenes/bookingDetail/tripDetails/TripDate.js, apps/core/scenes/search/PlacePicker/PlaceItem.js, apps/core/scenes/search/PlacePicker/PlacePickerContent.js, packages/components/package.json, packages/components/src/Illustration/Illustration.js, packages/components/src/TimelineFlightDetail/TimelineFlightDetail.js, packages/components/src/TimelineFlightDetail/components/CardHeader.js, packages/components/src/TimelineInformation/__tests__/__snapshots__/TimelineInformation.test.js.snap, packages/components/src/duration/__tests__/__snapshots__/Duration.test.js.snap, packages/components/src/passengerCard/__tests__/__snapshots__/PassengerCard.test.js.snap, packages/components/src/passengersInputs/PassengersInputsLine.js, packages/components/src/select/Select.js, packages/components/src/select/SelectOption.js, packages/components/src/shareIcon/ShareIcon.js, packages/components/src/text/Text.js, packages/components/src/text/__tests__/__snapshots__/Text.android.test.js.snap, packages/components/src/text/__tests__/__snapshots__/Text.ios.test.js.snap, packages/components/src/tripInput/__tests__/TripInput.test.js, packages/components/src/tripTypeButton/TripTypeButton.js, yarn.lock
Summary: Now that Flow types are correctly being picked up, there were quite a few Flow errors to fix.
Some are related to using react-native-web flow-typed in this repo and they conflict with `@kiwicom/universal-components` in `node_modules`. These will have to be fixed there and they are ignored in this repo in .flowconfig file.
There was also an issue with how Jest resolves `@kiwicom/universal-components`: it only looks at the `main` field in `package.json`, and not at `react-native` field if preset is `jest-expo` or `react-native` in the config file`.jest.json`. That means that Jest resolved the web version of the components instead of the RN version.
=> Chore: Upgrading @kiwicom/universal-components v0.0.13

apps/core/scenes/search/PlacePicker/PlacePickerContent.js, apps/core/scenes/search/PlacePicker/PlacePickerList.js
- enable autoFocus
- turn off autocorrect: It's annoying to write locations on iOS with autocorrect:
=> Fix autocorrect in PlacePicker

apps/graphql/src/dataloaders/Itinerariesloader.js
This is to ensure that the date sent in = the date we search for
no matter what timezone we run the code in
closes #301
=> Graphql: strip timezone offset for search dates

apps/core/components/ItineraryCard/FlightTimes.js, apps/core/components/ItineraryCard/StopoverDuration.js, apps/core/components/ItineraryCard/StopoverDurationWrapper.native.js, apps/core/components/ItineraryCard/StopoverDurationWrapper.web.js, apps/core/components/ItineraryCard/Transporters.js, apps/core/components/ItineraryCard/TripCities.js, apps/core/components/ItineraryCard/TripSector.js
Summary: Updated `TripSector` layout for web.
Note: Because of Relay fragments I wasn't able to use our usual approach with `TripSector.native/web.js`. And which component should be rendered is handled inside `RenderTripSectorItem`. Reason for this is that even that component content is similar for both platforms, the layout and nesting is completely different.
The other option is to merge both component into one `TripSector` and decide which layout should be used inside. But I find this approach slightly cleaner because we have both layouts separated to smaller components/files so it's easier to read.
=> Refactor: TripSector web layout

apps/core/scenes/search/Search.js, apps/mobile/App.js, apps/mobile/package.json, apps/web/pages/_app.js, packages/components/index.js, packages/components/src/alert/Alert.js, packages/components/src/alert/AlertContext.js
Summary: The current behaviour is to display the message only if both travelFrom and travelTo are null.
If you want to reproduce it you can replace in `SearchContext.js`
```
const defaultState = {
tripType: 'return',
travelFrom: null, // defaultPlaces.origin,
travelTo: null, // defaultPlaces.departure,
...
```
**EDIT**: This PR adds a new Alert component (together with a context to use it) in @kiwicom/margarita-components. It displays a Modal UI element on web and uses react-native's Alert on mobile.
Closes https://github.com/kiwicom/margarita/issues/276
=> Feat: Display warning if no locations

apps/core/components/ItineraryCard/TripSector.js, apps/core/components/ItineraryCard/TripSectorHelpers.js
Summary: Updated formatting to correctly handle duration longer than one day.
Before
After
Note: In next iteration we should move these helpers into `@kiwicom/margarita-utils` (it will be used by multiple components) and write proper tests for it.
=> Fix: Wrong sector hours duration

packages/components/src/duration/Duration.js, packages/components/src/duration/__tests__/__snapshots__/Duration.test.js.snap
Summary: `Duration` component text weight can be set to bold.
Required for `SectorDetail` header.
=> Feat: Added weight prop to Duration component

apps/documentation/pages/getting-started.md
Summary: `getting-started` was crashing because of wrong image path.
=> Fix: Updated img path in docs getting-started

.dependabot/config.yml
Summary: Added Dependabot config file and changed updates schedule to weekly.
More info about config options: https://dependabot.com/docs/config-file/#update_schedule-required
Note: Related to discussion: https://skypicker.slack.com/archives/CEFT2NAE8/p1550216049000500.
As mentioned on Dependabot website, this configuration doesn't affect security updates `We make an exception for security patches, which you'll always receive immediately.`.
=> Chore: Dependabot schedule changed to weekly

.circleci/config.yml
Summary: When merging `universal-components` into `margarita`, I added that build process in CircleCI. But since I also added a `postinstall` hook in `package.json` to build `universal-components`, it should not be necessary anymore.
=> Fix: Removed unnecessary build process

apps/landingPage/components/Header.js, apps/landingPage/pages/index.js
+ Add missing `<meta name="viewport" content="width=device-width, initial-scale=1" />`
+ Update mobile `Header`
For now I just put GitHub link instead of the menu button as we dont have design for the menu yet. Please let me know what you think
=> Update header landing page

packages/universal-components/src/TextInput/TextInput.js, packages/universal-components/src/TextInput/__tests__/__snapshots__/index.test.js.snap
Summary: Switched from system default fontFamily to `Roboto`.
Before:
After (Roboto is slightly more compact):
=> Fix: Set correct TextInput fontFamily

apps/core/scenes/search/Search.js
Summary: Updated mobile search screen layout for smaller devices.
Web version stays the same without any visible changes.
Closes #173
Before:
After:
Tablet:
=> Fix: Mobile Search layout

apps/core/components/ItineraryCard/FlightTimes.js, apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/ItineraryCard/ItineraryCardWrapper.web.js, apps/core/components/ItineraryCard/StopoverDurationWrapper.web.js, apps/core/components/ItineraryCard/TripSector.js, apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetailWrapper.web.js, apps/core/components/priceSummary/PriceSummary.js, apps/core/package.json, apps/core/scenes/passengerForm/PassengerForm.js, apps/core/scenes/results/Results.js, apps/web/next.config.js, packages/design-tokens/index.js, packages/design-tokens/package.json, packages/design-tokens/src/MargaritaTokens.js, packages/universal-components/package.json, packages/universal-components/src/Badge/Badge.js, packages/universal-components/src/Badge/styles/index.js, packages/universal-components/src/LocalizedPrice/LocalizedPrice.js
Summary: Added `@kiwicom/margarita-design-tokens` to store repeating style values which are currently missing in `orbit-design-tokens`.
Cleaned code from related todos.
Note: I've tried to use as generic names as possible where it makes sense. And kept original names if we just replacing actual value from orbit, like in case of badges.
But I'm definitely open to any other suggestions.
Closes #136
=> Feat: Added margarita-design-tokens package

packages/universal-components/src/Button/Button.stories.js, packages/universal-components/src/Button/ButtonTypes.js, packages/universal-components/src/Button/styles/shared.js
The `disabled` type did not necessarily set the HTML disabled property on the elements. Hence, the styling was applied (cursor, opacity) but the click events were actually performed. We got rid of the disabled type in favour of the html disabled prop which sets the styles and also prevents the click.
Fixes #473
=> Fix: Get rid of type 'disabled' in favour of the html disabled prop

apps/core/components/ItineraryCard/FlightTimes.js, apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/ItineraryCard/ItineraryCardWrapper.web.js, apps/core/components/ItineraryCard/StopoverDurationWrapper.web.js, apps/core/components/ItineraryCard/TripSector.js, apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetailWrapper.web.js, apps/core/components/priceSummary/PriceSummary.js, apps/core/components/sectorDetail/SectorHeader.js, apps/core/components/sectorDetail/segment/SegmentStopInfoRow.js, apps/core/package.json, apps/core/scenes/passengerForm/PassengerForm.js, apps/core/scenes/payment/Payment.js, apps/core/scenes/results/Results.js, apps/web/next.config.js, packages/components/package.json, packages/components/src/contentContainer/ContentContainer.js, packages/components/src/tripInput/TripInput.js, packages/design-tokens/index.js, packages/design-tokens/package.json, packages/universal-components/package.json, packages/universal-components/src/Badge/Badge.js, packages/universal-components/src/Badge/styles/index.js, packages/universal-components/src/Checkbox/CheckboxText.js, packages/universal-components/src/DesignTokens/DesignTokens.js, packages/universal-components/src/DesignTokens/index.js, packages/universal-components/src/FilterButton/FilterButton.js, packages/universal-components/src/FormFeedback/FormFeedback.js, packages/universal-components/src/LocalizedPrice/LocalizedPrice.js, packages/universal-components/src/index.js
Summary: Removes publishing blocking internal Margarita dependency.
Closes: #582
Note: I was thinking about also keeping `margarita-design-tokens`. But at the end I've decided to remove it. It will be probably confusing to have three different tokens. And as we previously discussed, for now this file should only contain repeating but still universal values and not margarita specific stuff like `colorTextDepartureTime`. So it quite makes sense to have these values as part of the `universal-components`.
=> Fix: Moved design tokens to universal-components

packages/universal-components/src/DesignTokens/DesignTokens.js, packages/universal-components/src/RangeDatePicker/DayItemArrow.js, packages/universal-components/src/RangeDatePicker/RenderDay.js, packages/universal-components/src/Touchable/Touchable.js
Animation is rendered only on iOS and web. On Android there are some problems with weird position of elements before the animation begins. It's probably connected with this one: https://github.com/facebook/react-native/issues/17510
It should be possible to resolve it after some time but it's probably not a priority right now.
=> Style arrows in RangeDatePicker

apps/graphql/src/apps/booking/Booking.js, apps/graphql/src/apps/booking/dataloaders/Bookings.js, apps/graphql/src/apps/common/CommonTypes.js, apps/graphql/src/apps/common/types/outputs/RouteStop.js, apps/graphql/src/apps/common/types/outputs/Sector.js, apps/graphql/src/apps/itinerary/Itinerary.js, apps/graphql/src/apps/itinerary/dataloaders/Itineraries.js, apps/graphql/src/apps/itinerary/dataloaders/Itinerary.js, apps/graphql/src/apps/itinerary/helpers/Itineraries.js, apps/graphql/src/apps/itinerary/helpers/__tests__/Itineraries.test.js, apps/graphql/src/apps/itinerary/types/outputs/Itinerary.js, schema.graphql
Summary:
- Merged Itinerary `endTime + destination` & `startTime + origin` to `arrival` & `departure` RouteStop types to make schema more consistent with bookings.
- Moved duplicate Itinerary and Booking flow types to `common` folder.
Before
After
=> Refactor: Duplicate types in Itinerary and Booking

apps/graphql/package.json, apps/mobile/index.js
This was needed when we used the in memory graphql fetch approach.
We now have the graphql deployed on a server, so we dont need this anymore
=> Remove buffer dependency

packages/components/storybook/webpack.config.js
Summary: Necessary after `@kiwicom/margarita-config` package update.
=> Fix: Margarita components webpack.config update

.jest.config.js, package.json
This checks which workspaces has been affected by code-changes
and runs the tests only for these workspaces.
There is no need to run the tests for unchanged workspaces
=> Use @kiwicom/monorepo run-tests

packages/universal-components/src/Button/ButtonContent.js, packages/universal-components/src/Button/ButtonInner.js, packages/universal-components/src/Button/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/Icon/IconTypes.js, packages/universal-components/src/Loader/Loader.js
Summary: Button loader is present in layout even if it's hidden.
Note: Maybe we can later refactor `ButtonInner` into two components to make insides slightly cleaner.
I've been also thinking about solving this issue directly inside `Loader` (simply returning `null` when `animating` is `false`). But at the and I think that handling it inside button is slightly better. There can be cases where hidden `Loader` inside layout can be required to prevent layout jumping while it is switched on/off.
=> Fix: Button loader visibility

packages/universal-components/src/RangeDatePicker/AnimatedDayItemArrow.js
I didn't want to use `scale` value as a prop from RangeDatePicker so it's now `static`. It believe it should not be a problem when we use it only for RangeDatePicker component. 
(Fixes #639)
=> Update synchronisation of animated arrows in RangeDatePicker

apps/graphql/.env-example
Summary: Recommended path in `.env` example should be to production server instead of test.
=> Fix: Updated example server path in .env

.gitignore, apps/web/package.json, netlify.toml, package.json, packages/universal-components/package.json, scripts/deploy.js
Summary: This is to better version control the build commands for Netlify, instead of relying on their UI, to which I only have access. This should be merged after https://github.com/kiwicom/margarita/pull/656.
It adds a deploy script that, based on an environment variable SITE_ID (that has to be set on Netlify's UI, sadly), will deploy the right site. This is a current limitation of `netlify.toml` as it does not support deploying multiple sites from one repository out of the box. (see https://github.com/netlify/netlify-cms/issues/1325 for more information)
=> Feat: adding back netlify.toml and deploy script

packages/universal-components/src/Modal/Modal.web.js
Add position `fixed` on web for the backdrop of the Modal to fix this issue.
Closes #665
=> Fix: Modal background opacity is not covering entire screen.

apps/core/scenes/results/Results.js, apps/core/scenes/search/Search.js, apps/core/scenes/search/SearchContext.js, apps/graphql/src/apps/itinerary/dataloaders/Itineraries.js, apps/mobile/src/screens/ResultsScreen.js
Summary: 
Selected passenger data are now used for search query.
So far we didn't passed any passenger data, which means that search used default `adults: 1` value.
=> Feat: Search passenger params

apps/graphql/package.json, apps/graphql/src/apps/manageMyBooking/dataloaders/Bookings.js, apps/graphql/src/apps/manageMyBooking/manageMyBooking.js
From current mmb, we get titles as lowercase.
Passenger title enum expects title to be capitalized.
closes #667
=> MMB: Capitalize passenger titles

apps/core/scenes/results/Results.js
`onSubmit` is not needed on the Results page. This is temporary,  on upcoming refactors, we will improve the Context/Navigation params obtention architecture.
=> QuickFix: Remove onSubmit from results

packages/universal-components/src/RangeDatePicker/RangeDatePickerContent.js
Before: 
after:
(Closes #660 )
=> Fix scrollbar interference in RangeDatePicker on web

apps/core/components/sectorDetails/ItinerarySectorDetails.js, apps/core/components/sectorDetails/__generated__/ItinerarySectorDetails_itinerary.graphql.js, apps/core/scenes/bookingDetail/sectorDetails/segments/SegmentContainer.js, apps/core/scenes/bookingDetail/sectorDetails/segments/__tests__/__snapshots__/SegmentContainer.test.js.snap, apps/core/scenes/resultDetail/ResultDetailInner.js, apps/core/scenes/resultDetail/__generated__/ResultDetailInnerQuery.graphql.js, apps/core/scenes/resultDetail/__generated__/ResultDetailInner_data.graphql.js, apps/core/scenes/resultDetail/__generated__/ResultDetailQuery.graphql.js, apps/core/scenes/resultDetail/resultDetailContent/ResultDetailContent.js, apps/core/scenes/resultDetail/resultDetailContent/__generated__/ResultDetailContent_itinerary.graphql.js, packages/components/index.js, packages/components/src/sectorDetailsWrapper/SectorDetailsWrapper.js
Summary:
- Extracted `SectorDetailsWrapper` from MMB sector details to make it reusable for results.
- Added expandable sector details to result. According to designs.
https://www.figma.com/file/OUhBJ9rPaTbRljptC0lrRrUF/Multistep
Top part of the header will follow in different PR.
=> Feat: Added sector details to ResultDetail

apps/web/components/Navbar.js, apps/web/components/__tests__/Navbar.test.js
To prevent underlying elements to be visible.
Before
After
=> Fix: Set Navbar background color

apps/core/scenes/results/Results.js, apps/core/scenes/search/Search.js, apps/core/scenes/search/SearchContext.js, apps/web/pages/index.js, apps/web/pages/results.js
The parameters are now kept on reloading (obtained from the URL and parsed into the context), on search and results. They are only updated when pressing search though...
=> Keep parameters on reloading (from URL)

apps/core/components/ItineraryCard/LocalTime.js, apps/core/components/ItineraryCard/TripSectorHelpers.js, apps/core/components/sectorDetail/segment/Segment.js, apps/core/components/sectorDetail/segment/SegmentStopInfo.js, apps/core/components/sectorInfo/SectorDate.js, packages/utils/src/FormatDate/FormatDate.js, packages/utils/src/FormatDate/__tests__/FormatDate.test.js
- Merged similar function `getFormattedDate` from `ItineraryCard` with `formatDate` inside `utils`.
- Which also fixed wrong time formatting in segments detail. Caused by timezone offset.
Response data:
```
local_departure: '2019-04-27T07:45:00.000Z',
local_arrival: '2019-04-27T08:50:00.000Z',
local_departure: '2019-04-27T13:00:00.000Z',
local_arrival: '2019-04-27T15:55:00.000Z',
```
---
Before
---
After
---
Same segments on kiwi.com
=> Fix: Date formatting

apps/graphql/src/apps/common/CommonTypes.js, apps/graphql/src/apps/itinerary/Itinerary.js, apps/graphql/src/apps/itinerary/dataloaders/Itineraries.js, apps/graphql/src/apps/itinerary/dataloaders/Itinerary.js, apps/graphql/src/apps/itinerary/helpers/Itineraries.js, apps/graphql/src/apps/itinerary/helpers/Itinerary.js, apps/graphql/src/apps/itinerary/queries/__tests__/__fixtures__/checkItinerary/CheckItinerary.graphql, apps/graphql/src/apps/itinerary/queries/__tests__/__fixtures__/itineraries/ItinerariesOneWay.graphql, apps/graphql/src/apps/itinerary/queries/__tests__/__fixtures__/itineraries/ItinerariesReturn.graphql, apps/graphql/src/apps/itinerary/queries/__tests__/__snapshots__/CheckItineraryQueries.test.js.snap, apps/graphql/src/apps/itinerary/queries/__tests__/__snapshots__/ItinerariesQueries.test.js.snap, apps/graphql/src/apps/itinerary/types/outputs/HoldBagOption.js, apps/graphql/src/apps/itinerary/types/outputs/ItineraryInterface.js, schema.graphql
Extended `Itinerary` object with `HoldBagOptions`.
Tequila bags options are currently slightly limited, because there is only hold bags info available and bookable on Booking endpoints.
This part will be extended later, after more bags options and combinations will be added to endpoints.
Closes: #689 
_Note:_
This part is currently mainly defined/limited by available bags options on booking endpoint, where you can simply just get and book from 1 to 3 hold bags for now.
For now partners should/can use (as it is implemented in this PR): 
- **Search API**: `bags_price`, `baglimit`
- **Booking API**: `bags_price`, `luggage`
(hopefully this mismatching baglimit/luggage naming will be also unified)
After some research I found out that baggage part is currently in active development and should …
=> Feat: Added HoldBagOptions to Itinerary

packages/universal-components/README.md, packages/universal-components/src/Hoverable/Hoverable.js, packages/universal-components/src/WithHover/__tests__/__snapshots__/withHover.test.js.snap, packages/universal-components/src/WithHover/__tests__/withHover.test.js, packages/universal-components/src/WithHover/index.js, packages/universal-components/src/WithHover/withHover.js, packages/universal-components/src/WithHover/withHover.stories.js, packages/universal-components/src/index.js
Summary: withHover HOC will provide us with a better way to check
if a component is hovered. Hoverable implementation was useless
and you had to do the work in each component using it anyways.
Also added a deprecation warning to hoverable component
closes #472
=> Feat: Add withHover HOC

apps/graphql/package.json, packages/universal-components/src/WithHover/__tests__/__snapshots__/withHover.test.js.snap, packages/universal-components/src/WithHover/__tests__/withHover.test.js, packages/universal-components/src/WithHover/withHover.js, packages/universal-components/src/WithHover/withHover.stories.js
Summary:Wrapping view caused malformed style when applied to components.
Instead inject the onMouseLeave and onMouseEnter through the HOC.
=> Refactor: Remove wrapping view from withHover

apps/documentation/i18n/en.json, apps/documentation/sidebars.json, docs/need-help.md
Sections removed because it looks duplicate to existing questions related section https://kiwicom.github.io/margarita/docs/questions-bugs-feature-requests
Maybe we can add some FAQ section later. But we will need to really gather some real questions first.
Closes #542
=> Docs: Removed 'Need help' section

README.md
Current readme file is outdated and full of TODOs. But in fact we already have most of these sections covered in documentation.
To prevent duplicate data (and need to maintain it in different places) readme was currently reduced to `demo` links, `documentation` link, few important `development` related links and `license`.
We can extend it later with some better project explanation. Once we obtain this content/copy for landing page.
New look: https://github.com/kiwicom/margarita/tree/docs/readme-revision
=> Docs: Readme update

apps/core/scenes/results/Results.js, apps/core/scenes/results/ResultsList.js, apps/web/components/Layout.js, apps/web/components/__tests__/Layout.test.js, packages/universal-components/src/PlatformStyleSheet/StyleTypes.js
Fixes #732 . Make all the body scrollable when there are search results instead of just the flat list, only in web version with mobile resolution. This allows seeing the results (before only a small frame appeared)
=> Feat: Make whole body scrollable when there are search results (On web with mobile res)

apps/core/scenes/results/Results.js, apps/core/scenes/results/__tests__/__snapshots__/ResultsList.test.js.snap
Updated style condition added in #735 , which unintentionally disabled flex layout also in mobile version.
Flex layout is correctly disabled only for mobile web version in updated version.
Before
After
=> Fix: Results flex style condition on mobile

apps/core/scenes/resultDetail/resultDetailContent/ResultDetailPassenger.js, packages/components/src/passengerCard/PassengerCard.js, packages/components/src/passengerCard/PassengerCardTypes.js, packages/components/src/passengerCard/__tests__/__snapshots__/PassengerCard.test.js.snap
Made insurance info optional and information block is rendered only if any insurance info is present in passenger data.
Insurance is currently not available for Tequila partners and this feature is currently not planned.
(but if it will be available one day, we will be ready)
=> Feat: Hide insurance info on PassengerCard

.circleci/config.yml
Test: On production, we add the variables to `graphql:deploy` using the CLI so they are set on the process from circleCI as we don't have `.env` there with those variables so the `serverless-dotenv-plugin` does not find anything.
=> Chore: Add env variables from CLI on production (no .env)

.circleci/config.yml, apps/graphql/src/apps/itinerary/types/inputs/common/ItineraryCommonSearchInputFields.js, schema.graphql
Change to trigger GraphQL server build on CircleCI with `env` variables set via CLI from the circleCI env variables so `serverless.yml` can get them (instead of getting them from a non-existent `.env` file)
=> Chore: change to test deploying graphql with env variables with CLI

.circleci/config.yml, apps/graphql/src/apps/itinerary/types/inputs/common/ItineraryCommonSearchInputFields.js, schema.graphql
Generating only the necessary fields on the `.env` to not overflow the limit set by AWS Lambda on environment variables (4kb)
=> Chore: Generate custom .env file for GraphQL

apps/core/components/searchForm/SearchForm.js, packages/components/src/tripInput/TripInput.js, packages/components/src/tripInput/__tests__/__snapshots__/TripInput.test.js.snap
Anywhere is placed instead on the PlacePickers when no place is selected. Due to limitations on `Tequila`, both places can't be empty at the same time but one of them can (either destination or origin), so a check that both aren't empty is performed on submit. Closes #766
=> Feature: Add anywhere text when no location selected on PlacePicker

apps/graphql/src/server.js
This is necessary for the landing page of Margarita
=> GraphQL: Playground has light theme by default

apps/core/scenes/resultDetail/resultDetailContent/ResultDetailPassenger.js
Closes #790 . Also, added validation that at least one passenger is required before going into the `Payment` screen of the booking process.
=> Refactor: Remove mock passenger data

apps/core/contexts/searchContext/SearchContext.js
I realized that we set the default state for the SearchContext from props, but I can't find any use case for that, and also props sending to SearchContext are different that flowTypes expected.
**PLEASE double check if I didn't miss something.**
=> Refactor: remove default state settings from props

apps/graphql/src/apps/location/Location.js, apps/graphql/src/apps/location/helpers/sanitizeLocation.js
The search failed when it contained a region because the Tequila response didn't contain a `location` field with a latitude, etc... so adding the null check there does the trick
Closes #824.
=> Fix: Location field can be null (for instance, in a region)

docs/packages/universal-components/contributing.md
I've noticed, that there's been broken relative link for commit template, so I've fixed it.
=> Docs: Fix link for commit template in contribution

apps/core/contexts/bookingContext/BookingContext.js, apps/core/contexts/searchContext/SearchContext.js, apps/core/scenes/resultDetail/ResultDetail.js, apps/core/scenes/results/Results.js, apps/core/scenes/search/Search.js, apps/web/pages/_app.js
**Summary**
- Hydrate the SearchContext from the URL at context creation
- Removed the `setStateFromQueryParams` from components `componentDidMount`, because it shouldn't be necessary.
- Moved the BookingToken from BookingContext to SearchContext, for code simplicity
(need to rethink if the `BookingContext` is necessary)
__________________________________________________________________________________
**Plan for next PRs**
- Move the SearchContexts parser methods to helper file, and write tests.
- Render empty PassengerCards based on count of passengers from SearchContex, similar behavior like on kiwi.com
=> Refactor the SearchContext

docs/apps/graphql/index.md, docs/demos.md
Removed stub text from demo section. 
Kept just two relevant demo links and moved remaining GraphQL related ones to `GraphQL Server` section.
Closes #862
=> Docs: Demo links

apps/core/components/searchForm/DatePicker.js, packages/universal-components/src/RangeDatePicker/RangeDatePicker.js, packages/universal-components/src/RangeDatePicker/RangeDatePicker.stories.js, packages/universal-components/src/RangeDatePicker/RangeDatePickerContent.js, packages/universal-components/src/RangeDatePicker/RangeDatePickerTypes.js, packages/universal-components/src/RangeDatePicker/__tests__/libs.test.js, packages/universal-components/src/RangeDatePicker/components/DraggableItem.ios.js, packages/universal-components/src/RangeDatePicker/components/DraggableItem.web.js, packages/universal-components/src/RangeDatePicker/components/RenderDay.js, packages/universal-components/src/RangeDatePicker/components/RenderMonth.js, packages/universal-components/src/RangeDatePicker/components/RenderWeek.js, packages/universal-components/src/RangeDatePicker/libs.js
- RangeDatePicker can be rendered from desired date (not only from today) by `renderFirstMonthFrom` props
- it's possible to use prop `isChoosingPastDatesEnabled` to enable selecting dates in history
Closes #828
=> Possibility of picking history dates in RangeDatePicker

packages/universal-components/src/Modal/Modal.native.js, packages/universal-components/src/Modal/__tests__/__snapshots__/Modal.test.js.snap, packages/universal-components/src/RangeDatePicker/RangeDatePicker.js
Removed default Modal margin in native version to make styling consistent across platforms.
Updated RangeDatePicker to fit modal content into view.
Closes #841
=> Fix: Unified Modal styling between platforms
