kiwicom/margarita

next.config.js, package.json, yarn.lock
=> add bundle analyzer

.env-sample, .gitignore, babel.config.js, next.config.js, package.json, packages/graphql/index.js, packages/graphql/package.json, packages/graphql/src/services/Fetch.js, yarn.lock
closes #11 
It works for web, but somehow times on mobile.
=> Graphql: Set up http service

packages/graphql/src/dataloaders/Itinerariesloader.js, packages/graphql/src/dataloaders/__tests__/Itinerariesloader.test.js, packages/graphql/src/queries/Itineraries.js, packages/graphql/src/types/input/ItinerariesSearchInput.js, packages/graphql/src/types/input/PassengersInput.js
=> Expand itinerariesSearch with more params

apps/web/pages/index.js, apps/web/pages/place-picker.js, apps/web/pages/results.js, package.json, packages/components/index.js, packages/components/src/Layout.js, packages/components/src/Navbar.js, packages/components/src/__tests__/Layout.test.js, packages/components/src/__tests__/Navbar.test.js, yarn.lock
=> Components: Add layout and navbar components

.eslintrc.js, .jest.json, apps/core/Search.js, apps/core/package.json, apps/web/babel.config.js, apps/web/next.config.js, apps/web/package.json, packages/components/Text.js, packages/components/src/Layout.js, packages/components/src/Navbar.js, yarn.lock
=> Add orbit tokens and universal components

.eslintrc.js, apps/core/Search.js, apps/web/babel.config.js, apps/web/package.json, packages/components/index.js, packages/components/src/Navbar.js, packages/components/src/TouchableWithoutFeedback.js, packages/components/src/__tests__/Navbar.test.js, packages/components/src/__tests__/TouchableWithoutFeedback.test.js, yarn.lock
Add TouchableWithoutFeedback component
=> Use universal-component buttons

apps/core/scenes/search/Search.js, packages/components/index.js, packages/components/src/TouchableWithoutFeedback.js, packages/components/src/tripInput/TripInput.js, packages/components/src/tripInput/__tests__/TripInput.test.js, packages/components/src/tripInput/__tests__/__snapshots__/TripInput.test.js.snap
=> Add trip input search component

apps/core/scenes/search/Search.js, packages/components/index.js, packages/components/src/passengersInputs/PassengersInputs.js, packages/components/src/passengersInputs/PassengersInputsHelpers.js, packages/components/src/passengersInputs/PassengersInputsLine.js, packages/components/src/passengersInputs/PassengersInputsTypes.js, packages/components/src/passengersInputs/__tests__/PassengersInputs.test.js, packages/components/src/passengersInputs/__tests__/__snapshots__/PassengersInputs.test.js.snap
To prevent confusion, name was changed (after short investigation) to `PassengersInputs` because there is already different component called `PassengerPicker` in designs - https://www.figma.com/file/WS4aFTwDfDHv6FL5Qawb0PR8/Passenger-Picker?node-id=0%3A1 .
But I'm definitely open to any other suggestions.
Closes #32
=> Add: PassengersInputs component

apps/web/babel.config.js, apps/web/package.json, package.json, yarn.lock
=> General: fix web build

yarn.lock
solved thanks @JoseDuSV 
closed #80
=> General: fix yarn lock

package.json
Following suggestion from https://github.com/kiwicom/margarita/pull/83#discussion_r244156449
=> Improve: flags in test script

apps/core/package.json, packages/components/package.json, yarn.lock
Reverts kiwicom/margarita#92
there is the issue with the PlaceCard Component which makes the app crash
=> Revert "Chore: Upgraded @kiwicom/universal-components to v0.0.7"

packages/components/index.js, packages/components/src/TimelineInformation/TimelineCabinBaggage.js, packages/components/src/TimelineInformation/TimelineDate.js, packages/components/src/TimelineInformation/TimelineDifferentAirport.js, packages/components/src/TimelineInformation/TimelineInformation.js, packages/components/src/TimelineInformation/TimelinePriorityBoarding.js, packages/components/src/TimelineInformation/__tests__/TimelineInformation.test.js, packages/components/src/TimelineInformation/__tests__/__snapshots__/TimelineInformation.test.js.snap, packages/components/src/TimelineInformation/index.js
Summary: Also contains specialised components TimelineCabinBaggage, TimelineDate, TimelineDifferentAirport and TimelineBoarding.
=> Feat: Added TimelineInformation component

packages/components/src/ConnectionCard/ConnectionCard.js, packages/components/src/ConnectionCard/HorizontalDash.js, packages/components/src/ConnectionCard/Timeline.js, packages/components/src/ConnectionCard/TimelineArrow.js, packages/components/src/ConnectionCard/TripSector.js
- Improve styling for arrival and departure time
- Almost pixel perfect arrow according to graphic design 😄 
- Dotted line between TripSectors and price
=> Better ConnectionCard styling

packages/components/index.js, packages/components/package.json, packages/components/src/TimelineFlightDetail/TimelineFlightDetail.js, packages/components/src/TimelineFlightDetail/components/AdditionalInfo.js, packages/components/src/TimelineFlightDetail/components/AdditionalInfoCard.js, packages/components/src/TimelineFlightDetail/components/CardHeader.js, packages/components/src/TimelineFlightDetail/index.js, packages/utils/helpers/__tests__/capitalize.test.js, packages/utils/helpers/capitalize.js, packages/utils/index.js, packages/utils/package.json, yarn.lock
Summary: This is how one can use the component:
```
<TimelineFlightDetail
carrier={{
code: 'FR',
name: 'Ryanair',
type: 'airline',
}}
additionalInfo={[
{
title: 'Connection Info',
information: [
{
icon: 'airplane-down',
label: 'Flight No',
value: 'OE 570',
},
{
icon: 'boarding-gate',
label: 'Departure terminal',
value: 'B7',
},
{
icon: 'boarding-gate',
label: 'Destination Terminal',
value: 'A2',
},
],
},
{
title: 'Seating Info',
information: [
{
icon: 'seat',
label: 'Seat pitch',
value: '36-38"',
},
{
icon: 'seat',
label: 'Seat width',
value: '17"',
},
{
icon: 'seat',
label: 'Seat recline',
value: '3"',
},
{
icon: 'entertainment',
label: 'Audio & video on demand',
value: 'Yes',
},
{
icon: 'power-plug',
label: 'In-seat power',
value: 'Yes',
},
{
icon: 'wifi',
label: 'WiFi on board',
value: …
```
=> Feat: Added TimelineFlightDetail component

apps/mobile/package.json, apps/mobile/scripts/configureApplication.js, apps/mobile/scripts/patch-get-yarn-workspaces.sh, package.json, packages/utils/index.js, packages/utils/localization/CurrencyFormatter.js, packages/utils/localization/DateFormatter.js, packages/utils/localization/DateUtils.js, packages/utils/localization/GetDeviceLocale.js, packages/utils/localization/GetDeviceLocale.native.js, packages/utils/localization/__mocks__/GetDeviceLocale.js, packages/utils/localization/__mocks__/GetDeviceLocale.native.js, packages/utils/localization/__tests__/DateFormatter.test.js, packages/utils/localization/__tests__/DateUtils.test.js, yarn.lock
Summary: Date and Currency Formatters, extracted from mobile repository, rely on Intl library, which needs to be patched for it to work on Android.
This lead to a rewrite of the other patch in apps/mobile in Node, to have all the patches in the same file.
=> Feat: Added Date and Currency Formatters

apps/graphql/package.json, apps/graphql/server.js, apps/graphql/src/services/Fetch.js, apps/graphql/src/services/Logger.js, apps/graphql/src/services/__tests__/Logger.test.js, apps/graphql/src/services/__tests__/__snapshots__/Logger.test.js.snap, yarn.lock
Added the simple graphql Logger for nicer messages at a console in the development environment.
=> Feat: Added GraphQL Logger

.env-sample, README.md, apps/graphql/.env-example, apps/graphql/server.js, apps/graphql/src/dataloaders/Itinerariesloader.js, apps/graphql/src/dataloaders/Locationsloader.js, apps/graphql/src/services/Fetch.js, apps/graphql/src/services/GraphQLContext.js, apps/graphql/src/services/TestingTools.js, packages/relay/src/Environment.js
This reverts commit 383ebc262ac22ce0132f1466344caacde604a0ad.
=> Revert "Move apikey to client"

README.md
Summary: We all sort of forgot that this was a thing to do on Android, so it is worth recording somewhere!
Closes #130
=> Docs: Expanded README about port forwarding on Android

apps/graphql/src/dataloaders/Itinerariesloader.js, package.json, yarn.lock
=> Replace luxon with date-fns

.eslintignore, apps/graphql/src/dataloaders/Itinerariesloader.js, apps/graphql/src/dataloaders/__tests__/Itinerariesloader.test.js, yarn.lock
TEMP: added default limit for the Tequila's search API
=> TEMP: added default limit for the Tequila's search API

apps/mobile/App.js, apps/mobile/src/navigation/SearchStack.js, apps/mobile/src/navigation/TabNavigator.js, apps/web/components/Navbar.js, apps/web/components/NavbarLink.js, apps/web/components/__tests__/Navbar.test.js, apps/web/components/__tests__/NavbarLink.test.js, apps/web/pages/mmb/index.js, packages/components/src/TouchableWithoutFeedback.js, packages/navigation/config/routes.js, yarn.lock
=> Add bottom tab navigation, and navbar links for web

apps/core/scenes/search/Datepickers.js, apps/core/scenes/search/Placepickers.js, apps/core/scenes/search/Search.js, apps/core/scenes/search/SearchConstants.js, apps/core/scenes/search/SearchModal.js, packages/components/src/IllustrationWithInformation/IllustrationWithInformation.js
Spreading responsabilities to more components.
For next interation I want to move state to a context
=> Refactor Search scene

.flowconfig, apps/graphql/package.json, apps/graphql/src/Schema.js, apps/graphql/src/datasets/AllBookings.json, apps/graphql/src/executeTestQuery.js, apps/graphql/src/queries/CustomerBookings.js, apps/graphql/src/queries/__tests__/__fixtures__/CustomerBookings.graphql, apps/graphql/src/queries/__tests__/__snapshots__/queries.test.js.snap, apps/graphql/src/queries/__tests__/queries.test.js, apps/graphql/src/types/output/CustomerBookings.js, yarn.lock
This will return mocked data for all bookings.
This query will be used to show list of user bookings
=> Add customer bookings query

apps/core/index.js, apps/core/scenes/bookings/Bookings.js, apps/core/scenes/bookings/__generated__/BookingsQuery.graphql.js, apps/mobile/src/navigation/MMBStack.js, apps/mobile/src/navigation/TabNavigator.js, apps/mobile/src/screens/BookingsListScreen.js, apps/mobile/src/screens/index.js, apps/web/pages/mmb/index.js, packages/navigation/config/routes.js, schema.graphql
Use bookings scene in web and mmb stack.
Add graphql query in bookings scene
=> Add MMBStack, add bookings scene

apps/graphql/package.json, apps/graphql/src/dataloaders/BookingsLoader.js, apps/graphql/src/queries/__tests__/__fixtures__/CustomerBookings.graphql, apps/graphql/src/queries/__tests__/__snapshots__/queries.test.js.snap, apps/graphql/src/types/output/CustomerBookings.js, apps/graphql/src/types/output/RouteStop.js, apps/graphql/src/types/output/SegmentTime.js, yarn.lock
These are the fields necessary for creating the MMB bookingslist
=> Add arrival, departure, destinationImageUrl and passenger count

apps/graphql/src/dataloaders/__tests__/itinerariesHelpers.test.js
=> Replace toBe(null) with toBeNull in itinerariesHelpers.test

apps/core/scenes/bookings/Booking.js, apps/core/scenes/bookings/BookingBadges.js, apps/core/scenes/bookings/BookingList.js, apps/core/scenes/bookings/Bookings.js, apps/core/scenes/bookings/__generated__/Booking.graphql.js, apps/core/scenes/bookings/__generated__/BookingBadges.graphql.js, apps/core/scenes/bookings/__generated__/BookingList.graphql.js, apps/core/scenes/bookings/__generated__/BookingsQuery.graphql.js, schema.graphql
For next iterations:
show From -> to, date, passengers
Improve layout for web
=> MMB: Add booking list, show cityImage with status and id

apps/graphql/package.json, apps/graphql/src/services/Fetch.js, yarn.lock
Unfortunately, I have no idea how to try it so please try it first.
=> GraphQL: use '@kiwicom/fetch' for fetching

apps/core/scenes/bookings/Booking.js, apps/core/scenes/bookings/__generated__/Booking.graphql.js, apps/core/scenes/bookings/__generated__/BookingsQuery.graphql.js, apps/mobile/src/navigation/MMBStack.js, apps/mobile/src/screens/BookingDetailScreen.js, apps/mobile/src/screens/index.js, apps/web/pages/mmb/booking-detail.js, packages/navigation/config/routes.js, packages/navigation/src/withNavigation.js
Fix flow types in withNavigation HOC
=> MMB: Add navigation to booking-detail screen

apps/graphql/package.json, apps/mobile/package.json, apps/web/package.json, package.json, yarn.lock
- webpack 4.29.1
- webpack-cli 3.2.3
- expo 32.0.4
-  @kiwicom/eslint-config 2.7.0
- eslint 5.13.0
- react-test-renderer 16.7.0
=> Chore: update dependencies

.circleci/config.yml
Summary: If ESLint, Flow and Jest can run concurrently, our CI should be faster as a result.
=> Chore: Improving CircleCI config

apps/core/index.js, apps/core/scenes/bookingDetail/BookingDetail.js, apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/bookingDetail/tripDetails/Header.js, apps/core/scenes/bookingDetail/tripDetails/TripDetails.js, apps/core/scenes/bookingDetail/tripDetails/__generated__/Header.graphql.js, apps/core/scenes/bookingDetail/tripDetails/__generated__/TripDetails.graphql.js, apps/mobile/src/screens/BookingDetailScreen.js, apps/web/pages/mmb/booking-detail.js, schema.graphql
=> MMB: Add booking status header

apps/graphql/src/dataloaders/BookingsLoader.js, apps/graphql/src/dataloaders/Locationsloader.js, apps/graphql/src/queries/__tests__/Locations.test.js, apps/graphql/src/services/GraphQLContext.js, apps/graphql/src/types/output/Location.js, apps/graphql/src/types/output/RouteStop.js
Add airport field to RouteStop
=> GraphQL: Add countryFlagUrl to Location

apps/core/scenes/search/Datepickers.js, apps/core/scenes/search/PickersWrapper.js, apps/core/scenes/search/Placepickers.js, apps/core/scenes/search/Search.js, apps/core/scenes/search/SearchFormModes.js, apps/mobile/App.js, apps/web/components/Layout.js, apps/web/components/__tests__/Layout.test.js, packages/components/index.js, packages/components/src/passengersButton/PassengersButton.js, packages/components/src/passengersButton/PassengersButton.native.js, packages/components/src/passengersButton/PassengersButtonTypes.js, packages/components/src/passengersButton/__tests__/PassengersButton.test.js, packages/components/src/passengersButton/__tests__/__snapshots__/PassengersButton.test.js.snap, packages/components/src/tripInput/TripInput.js, packages/components/src/tripInput/__tests__/__snapshots__/TripInput.test.js.snap, packages/components/src/tripTypeSwitch/TripTypeSwitch.js, packages/components/src/tripTypeSwitch/TripTypeSwitchOption.js, packages/components/src/tripTypeSwitch/__tests__/TripTypeSwitch.test.js, packages/components/src/tripTypeSwitch/__tests__/__snapshots__/TripTypeSwitch.test.js.snap, packages/utils/index.js, packages/utils/layoutContext/LayoutConstants.js, packages/utils/layoutContext/LayoutContext.js, packages/utils/layoutContext/LayoutContextHelpers.js, packages/utils/layoutContext/__tests__/LayoutContextHelpers.test.js
Summary:
Updated search form styles and components structure for responsive web layout.
Added web version of `PassengersButton`.
Added `TripTypeSwitch` component which replaces `TripTypeButton` in web version.
Added `LayoutContext` which provide `layout` prop for responsive layouts.
Closes #147
=> Feat: SearchForm web layout

.eslintignore, apps/landingPage/gatsby-config.js, apps/landingPage/package.json, apps/landingPage/src/components/Demo.js, apps/landingPage/src/components/Header.js, apps/landingPage/src/components/Info.js, apps/landingPage/src/pages/404.js, apps/landingPage/src/pages/index.js, package.json, yarn.lock
Refactor inline styles to styled components, add airport image
Update Playground design
Change playground size according to window size
Add config file for the project related links
Update design in showcase and features part
Update design of the bottom part of the page
Update footer according to new design
Remove unused styles
Fix: restore styles and images after rebase
Chore: remove unnecessary  RelativeImageStub comments
Chore: change component naming case and linksConfig
Remove placeholder links
Add gh-pages deploy script
Update yarn.lock
fix: refactor pages to React classes
check if window undefined, so gatsby can do build
Add missing buttons
=> Update landingPage according to the new design

apps/core/components/fromTo/FromTo.js, apps/core/components/fromTo/FromToIcon.js, apps/core/components/fromTo/__generated__/FromTo.graphql.js, apps/core/components/fromTo/__generated__/FromToIcon.graphql.js, apps/core/components/fromTo/__tests__/FromToIcon.test.js, apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/bookings/__generated__/BookingsQuery.graphql.js, flow-typed/npm/jest_v24.x.x.js, package.json, packages/relay/src/__mocks__/Environment.js, scripts/setupTests.js, yarn.lock
Multicity, return and one way should all have different icon
=> MMB: Add component for showing correct trip type icon

apps/core/index.js, apps/core/scenes/bookingDetail/BookingDetail.js, apps/core/scenes/bookingDetail/BookingDetailWrapper.js, apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/bookingDetail/__generated__/BookingDetailWrapper.graphql.js, apps/core/scenes/bookingDetail/menuGroups/Manage.js, apps/core/scenes/bookings/BookingList.js, apps/core/scenes/manageHelp/ManageHelp.js, apps/core/scenes/manageOther/ManageOther.js, apps/core/scenes/shareBooking/ShareBooking.js, apps/mobile/src/navigation/MMBStack.js, apps/mobile/src/screens/ManageHelpScreen.js, apps/mobile/src/screens/ManageOtherScreen.js, apps/mobile/src/screens/ShareBookingScreen.js, apps/mobile/src/screens/index.js, apps/web/pages/mmb/booking-detail.js, apps/web/pages/mmb/components/Wrapper.js, apps/web/pages/mmb/help.js, apps/web/pages/mmb/other.js, apps/web/pages/mmb/share-booking.js, packages/components/index.js, packages/components/src/shareIcon/ShareIcon.js, packages/components/src/shareIcon/__tests__/ShareIcon.android.test.js, packages/components/src/shareIcon/__tests__/ShareIcon.ios.test.js, packages/components/src/shareIcon/__tests__/ShareIcon.web.test.js, packages/components/src/shareIcon/__tests__/__snapshots__/ShareIcon.android.test.js.snap, packages/components/src/shareIcon/__tests__/__snapshots__/ShareIcon.ios.test.js.snap, packages/components/src/shareIcon/__tests__/__snapshots__/ShareIcon.web.test.js.snap, packages/navigation/config/routes.js
Summary: I also prepared screens for the corresponding routes. The route configurations might need to be improved, especially when I suspect that the booking id might be necessary for the Share Booking screen for instance.
=> Feat: Manage Menu Group added to Booking Detail screen

apps/core/index.js, apps/core/scenes/bookingDetail/BookingDetailWrapper.js, apps/core/scenes/bookingDetail/menuGroups/Services/Footer.js, apps/core/scenes/bookingDetail/menuGroups/Services/Services.js, apps/core/scenes/bookingDetail/menuGroups/Services/index.js, apps/core/scenes/flightServices/FlightServices.js, apps/core/scenes/tripServices/TripServices.js, apps/mobile/src/navigation/MMBStack.js, apps/mobile/src/screens/FlightServicesScreen.js, apps/mobile/src/screens/TripServicesScreen.js, apps/mobile/src/screens/index.js, apps/web/pages/mmb/flight-services.js, apps/web/pages/mmb/trip-services.js, packages/navigation/config/routes.js
Summary: Basic setup for Services menu group; All Services section should be fetched dynamically.
Closes #164
=> Feat: Services Menu Group

apps/core/index.js, apps/core/scenes/bookingDetail/BookingDetailWrapper.js, apps/core/scenes/bookingDetail/menuGroups/TripInfo.js, apps/core/scenes/tickets/Tickets.js, apps/core/scenes/timeline/Timeline.js, apps/mobile/src/navigation/MMBStack.js, apps/mobile/src/screens/TicketsScreen.js, apps/mobile/src/screens/TimelineScreen.js, apps/mobile/src/screens/index.js, apps/web/pages/mmb/tickets.js, apps/web/pages/mmb/timeline.js, packages/navigation/config/routes.js
Closes #162 
DESIGN: https://www.figma.com/file/BNs81bMp3VVuxqKIICbnNvqd/MMB?node-id=1%3A193
=> Feat: Trip Info Menu Group

apps/core/components/fromTo/FromTo.js, apps/core/components/fromTo/FromToIcon.js, apps/core/components/fromTo/__generated__/FromToIcon.graphql.js, apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/bookingDetail/tripDetails/TripDate.js, apps/core/scenes/bookingDetail/tripDetails/TripDates.js, apps/core/scenes/bookingDetail/tripDetails/TripDetails.js, apps/core/scenes/bookingDetail/tripDetails/TripInfo.js, apps/core/scenes/bookingDetail/tripDetails/TripInfoOneWay.js, apps/core/scenes/bookingDetail/tripDetails/__generated__/TripDate.graphql.js, apps/core/scenes/bookingDetail/tripDetails/__generated__/TripDates.graphql.js, apps/core/scenes/bookingDetail/tripDetails/__generated__/TripDetails.graphql.js, apps/core/scenes/bookingDetail/tripDetails/__generated__/TripInfo.graphql.js, apps/core/scenes/bookingDetail/tripDetails/__generated__/TripInfoOneWay.graphql.js, apps/core/scenes/bookings/__generated__/BookingsQuery.graphql.js, apps/graphql/src/types/output/BookingMulticity.js, apps/graphql/src/types/output/BookingOneWay.js, apps/graphql/src/types/output/BookingReturn.js, apps/graphql/src/types/output/FromToInterface.js, apps/graphql/src/types/output/Trip.js, packages/components/index.js, packages/components/src/duration/Duration.js, packages/components/src/duration/__tests__/Duration.test.js, packages/components/src/duration/__tests__/__snapshots__/Duration.test.js.snap, schema.graphql
Add an interface to be able to re-use FromTo component
for list view and booking detail header.
Add duration component
=> MMB: Show trip dates and time for one way booking

packages/components/index.js, packages/components/src/passengerCard/BagInformation.js, packages/components/src/passengerCard/PassengerCard.js, packages/components/src/passengerCard/PassengerCardDetail.js, packages/components/src/passengerCard/__tests__/PassengerCard.test.js, packages/components/src/passengerCard/__tests__/__snapshots__/PassengerCard.test.js.snap
=> Add PassengerCard component

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/ItineraryCard/ItineraryCardRow.js, apps/core/scenes/results/ResultsList.js
Summary: Updated `ResultsList` and `ItineraryCard` web-related styles and conditions.
`TripSector` web layout will be updated in next PR.
@jvaclavik Do you have any plans with `ItineraryCardRow` component? As you can see I just updated its styles but I'm not sure if this wrapper is really necessary. This padding can probably be directly part of the `TripSector` component.
Related to #112
=> Refactor: Added ResultsList web layout

apps/core/scenes/bookings/BookingBadges.js, packages/utils/helpers/__tests__/capitalize.test.js, packages/utils/helpers/capitalize.js
Currently we showed green background no matter status
=> MMB: Booking badges correct background color

apps/core/config.js, apps/core/package.json, apps/core/scenes/bookingDetail/tripDetails/TripDate.js, apps/core/scenes/bookings/DateAndPassengerCount.js, apps/core/scenes/search/PlacePicker/PlacePickerContent.js, apps/web/next.config.js, packages/config/index.js, packages/config/package.json
Better to have a package that can be used across other apps/packages
=> Create new config package and move config variables there

apps/core/components/fromTo/FromToWrapper.js, apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/bookingDetail/tripDetails/TripDate.js, apps/core/scenes/bookingDetail/tripDetails/TripDetails.js, apps/core/scenes/bookingDetail/tripDetails/TripInfo.js, apps/core/scenes/bookingDetail/tripDetails/TripInfoReturn.js, apps/core/scenes/bookingDetail/tripDetails/__generated__/TripDetails.graphql.js, apps/core/scenes/bookingDetail/tripDetails/__generated__/TripInfoReturn.graphql.js, packages/components/index.js, packages/components/src/bookingTypeRenderer/BookingTypeRenderer.js, packages/components/src/bookingTypeRenderer/__tests__/BookingTypeRenderer.test.js, packages/utils/index.js, packages/utils/src/__tests__/formatDate.test.js, packages/utils/src/formatDate.js
Add component for rendering correct booking trip type
Add wrapper around date-fns-format to adjust for timezone
closes #161
=> MMB: Add return trip info

apps/core/scenes/search/PlacePicker/PlaceItem.js, apps/core/scenes/search/PlacePicker/PlacePickerContent.js, apps/core/scenes/search/PlacePicker/PlacePickerList.js, apps/core/scenes/search/PlacePicker/PlacePickerRenderer.js
**Web**
Before:
After:
**iOS**
Before:
After:
Btw why there is **Austria** when I search for **os**?
=> Style place picker modal

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/ItineraryCard/ItineraryCardWrapper.native.js, apps/core/components/ItineraryCard/ItineraryCardWrapper.web.js
Summary: Added responsive layout to web version of `ItineraryCard`.
Extracted platform specific parts into separate `ItineraryCardWrapper` component. Because original component started to be hard to read with condition combinations like: web platform && mobile layout.
=> Refactor: Added ItineraryCardWrapper component

apps/core/scenes/results/Results.js, apps/core/scenes/search/Search.js, apps/mobile/src/screens/ResultsScreen.js
=> Update header text in results

apps/core/scenes/bookings/Booking.js
=> Update proper aspect ratio of images in MMB

.eslintrc.js, apps/core/package.json, apps/graphql/package.json, apps/mobile/package.json, apps/web/package.json, package.json, packages/components/package.json, packages/relay/package.json, packages/utils/package.json
=> Eslint: Enable import/no-extraneous-dependencies

packages/relay/src/QueryRenderer.js
=> Replace react-relay QueryRenderer with @kiwicom/relay QueryRenderer

apps/core/components/ItineraryCard/FlightTimes.js, apps/core/components/ItineraryCard/LocalTime.js, apps/core/components/ItineraryCard/LocationName.js, apps/core/components/ItineraryCard/RenderTripSectorItem.js, apps/core/components/ItineraryCard/TripCities.js, apps/core/components/ItineraryCard/TripSector.js, apps/core/components/ItineraryCard/__generated__/FlightTimes.graphql.js, apps/core/components/ItineraryCard/__generated__/LocalTime.graphql.js, apps/core/components/ItineraryCard/__generated__/LocationName.graphql.js, apps/core/components/ItineraryCard/__generated__/RenderTripSectorItem.graphql.js, apps/core/components/ItineraryCard/__generated__/TripCities.graphql.js, apps/core/components/ItineraryCard/__generated__/TripSector.graphql.js, apps/core/scenes/results/__generated__/ResultsQuery.graphql.js, apps/graphql/src/types/output/Sector.js, schema.graphql
Delete deprecated fields on Sector type
=> Refactor: Use RouteStop on sector type

apps/graphql/src/dataloaders/bookingsLoader/BookingDetailLoader.js, apps/graphql/src/dataloaders/bookingsLoader/BookingFlowTypes.js, apps/graphql/src/dataloaders/bookingsLoader/BookingsLoader.js, apps/graphql/src/types/output/BookingInterface.js, apps/graphql/src/types/output/ContactDetails.js, apps/graphql/src/types/output/Passenger.js
Summary: Querying passengers and contact details from `AllBookings.json`
Note: `visaRequired` field is **hardcoded** and set to `false` for now
=> Query passengers and contact details

apps/documentation/.gitignore, apps/documentation/babel.config.js, apps/documentation/next.config.js, apps/documentation/package.json, apps/documentation/pages/_app.js, apps/documentation/pages/_document.js, apps/documentation/pages/apps/index.md, apps/documentation/pages/apps/mobile/index.md, apps/documentation/pages/apps/web/index.md, apps/documentation/pages/getting-started.md, apps/documentation/pages/index.md, package.json, yarn.lock
Summary: These docs were kickstarted using `npm init docs` and use NextJs. It's a pretty basic setup and we wouldneed to create more components and custom logic to have a nicer feel to them. I also believe the styling could be improved (https://github.com/jxnblk/mdx-docs/blob/master/docs/pages/theming.md).
Let's start documenting!
Note: I am not sure how to keep in sync our README.md at the root of the repo; we could potentially add a route in `_app.js` that somehow points to a file higher up in the folder structure and remove the `index.md` file in `apps/documentation`.
=> Feat: Adding documentation for Margarita

apps/web/package.json, package.json, yarn.lock
Reverts #336
After dependency update Next.js project rebuilding on file change stopped working.
=> Revert "Chore(deps): Bump next-plugin-transpile-modules"

apps/core/index.js, apps/core/scenes/bookingDetail/BookingDetailWrapper.js, apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/Passenger.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/Passengers.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/PassengersList.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/VisaDetail.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/__generated__/Passenger.graphql.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/__generated__/Passengers.graphql.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/__generated__/PassengersList.graphql.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/__generated__/VisaDetail.graphql.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/index.js, apps/core/scenes/passengerDetail/PassengerDetail.js, apps/mobile/src/navigation/MMBStack.js, apps/mobile/src/screens/PassengerDetailScreen.js, apps/mobile/src/screens/index.js, apps/web/pages/mmb/passenger-detail.js, packages/navigation/config/routes.js, yarn.lock
Summary: add passenger menu group component + navigation to passenger detail
Note: bags part is missing in this PR
Closes #163
=> Feat: add passenger menu group component

apps/core/components/ItineraryCard/LocationName.js, apps/core/components/ItineraryCard/RenderTripSectorItem.js, apps/core/components/ItineraryCard/__generated__/LocationName.graphql.js, apps/core/components/ItineraryCard/__generated__/RenderTripSectorItem.graphql.js, apps/core/components/fromTo/CityName.js, apps/core/components/fromTo/__generated__/CityName.graphql.js, apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/bookings/__generated__/BookingsQuery.graphql.js, apps/core/scenes/results/__generated__/ResultsQuery.graphql.js, apps/graphql/src/dataloaders/Locationsloader.js, apps/graphql/src/dataloaders/LocationsloaderTypes.js, apps/graphql/src/dataloaders/itinerariesHelpers.js, apps/graphql/src/queries/__tests__/Locations.test.js, apps/graphql/src/queries/__tests__/__fixtures__/BookingDetail.graphql, apps/graphql/src/queries/__tests__/__fixtures__/CustomerBookings.graphql, apps/graphql/src/queries/__tests__/__fixtures__/Itineraries.graphql, apps/graphql/src/queries/__tests__/__snapshots__/Locations.test.js.snap, apps/graphql/src/queries/__tests__/__snapshots__/queries.test.js.snap, apps/graphql/src/types/output/Location.js, apps/graphql/src/types/output/RouteStop.js, schema.graphql
Rename airport to stop, since it could be any kind of stop
see discussion in #322
=> Graphql: Remove cityId from RouteStop type

apps/core/scenes/bookingDetail/sectorDetails/SectorDetails.js, apps/core/scenes/bookingDetail/sectorDetails/SectorInfoMulticity.js, apps/core/scenes/bookingDetail/sectorDetails/segments/SegmentContainer.js, apps/core/scenes/bookingDetail/sectorDetails/segments/__tests__/SegmentContainer.test.js, apps/core/scenes/bookingDetail/sectorDetails/segments/__tests__/__snapshots__/SegmentContainer.test.js.snap
Add animation for icon on click
=> MMB: Add expand button with icon under sector info

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/ItineraryCard/ItineraryCardWrapper.native.js, apps/core/components/ItineraryCard/ItineraryCardWrapper.web.js, apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetail.js, apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetailWrapper.native.js, apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetailWrapper.web.js, apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetailWrapperTypes.js
Summary: Implemented `ItineraryDetail` component for both platforms.
On web content is displayed in expandable area inside `ItineraryCard`. And on mobile content is displayed inside `Modal`.
Component will be filled with data in next PR.
Related to #70
=> Feat: Added ItineraryDetail component

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/ItineraryCard/ItineraryCardWrapper.native.js
=> Replace styles in ItineraryCard with Card from universal-components

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetail.js, apps/core/index.js, apps/core/scenes/resultDetail/ResultDetail.js, apps/core/scenes/results/ResultsList.js, apps/mobile/src/navigation/SearchStack.js, apps/mobile/src/screens/ResultDetailScreen.js, apps/mobile/src/screens/index.js, apps/web/pages/result-detail.js, packages/navigation/config/routes.js
Creating empty screen for ResultDetail (#366)
=> Create empty ResultDetailScreen

packages/components/src/timelineInformation/TimelineCabinBaggage.js, packages/components/src/timelineInformation/TimelineDate.js, packages/components/src/timelineInformation/TimelineDifferentAirport.js, packages/components/src/timelineInformation/TimelineInformation.js, packages/components/src/timelineInformation/TimelinePriorityBoarding.js, packages/components/src/timelineInformation/__tests__/__snapshots__/TimelineInformation.test.js.snap
Summary: Enabled container styling on all `TimelineInformation` types, required for itinerary detail. Small style update to align icon with `TimelineTransportDetail` line.
=> Feat: Extended TimelineInformation styling

apps/graphql/src/apps/itinerary/helpers/Itineraries.js, apps/graphql/src/apps/location/Location.js, apps/graphql/src/apps/location/dataloaders/Locations.js, apps/graphql/src/apps/location/queries/__tests__/__fixtures__/LocationsByTerm.graphql, apps/graphql/src/apps/location/queries/__tests__/__snapshots__/LocationsQueries.test.js.snap, apps/graphql/src/apps/location/types/enums/LocationType.js, apps/graphql/src/apps/location/types/outputs/Location.js
Added type field into the Location schema.
=> Feat: Add type into the GraphQL Location schema

apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/Bag.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/Passenger.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/PassengersList.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/VisaDetail.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/__generated__/Bag.graphql.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/__generated__/PassengersList.graphql.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/__tests__/Bag.test.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/__tests__/__snapshots__/Bag.test.js.snap, apps/graphql/src/apps/booking/Booking.js, apps/graphql/src/apps/booking/dataloaders/Bookings.js, apps/graphql/src/apps/booking/types/outputs/Bag.js, apps/graphql/src/apps/booking/types/outputs/BagType.js, apps/graphql/src/apps/booking/types/outputs/BookingInterface.js, apps/graphql/src/apps/booking/types/outputs/Passenger.js, apps/graphql/src/apps/booking/types/outputs/__tests__/BookingInterface.test.js, apps/graphql/src/types/output/Bag.js, apps/graphql/src/types/output/BagType.js, apps/mobile/src/navigation/MMBStack.js, schema.graphql, yarn.lock
Summary: Add bags total count by type to the passengers' detail.
=> Feat: add bags details to the passenger detail component

apps/core/scenes/bookingDetail/BookingDetailWrapper.js, apps/mobile/src/screens/BookingDetailScreen.js, apps/web/components/Navbar.js, apps/web/components/Wrapper.js, apps/web/components/__tests__/Navbar.test.js
Using div instead of View broke the functionality of nested scroll view.
It no longer scrolled
=> MMB: Use View instead of div in mmb-Wrapper

apps/graphql/lambda/graphql.js
=> Fix: allow the "X-Client" header for lambda GraphQL

apps/landingPage/src/components/Demo.js, apps/landingPage/src/components/Footer.js, apps/landingPage/src/components/GetStartedInfo.js, apps/landingPage/src/components/Header.js, apps/landingPage/src/components/Headline.js, apps/landingPage/src/components/Info.js, apps/landingPage/src/components/Playground.js, apps/landingPage/src/components/withWindowSize.js, apps/landingPage/src/pages/index.js
Summary: update styling
Note:
+ iframe size is bigger than in design otherwise would be almost impossible to use
+ header is still not implemented
=> Update LandingPage mobile styling

apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/bookingDetail/sectorDetails/segments/SegmentMap.js, apps/core/scenes/bookingDetail/sectorDetails/segments/SegmentMapMarker.js, apps/core/scenes/bookingDetail/sectorDetails/segments/__generated__/SegmentMap.graphql.js, apps/core/scenes/bookingDetail/sectorDetails/segments/__generated__/SegmentMapSegment.graphql.js, apps/core/scenes/bookingDetail/sectorDetails/segments/__generated__/SegmentMapStop.graphql.js, apps/core/scenes/bookingDetail/sectorDetails/segments/__tests__/SegmentMap.test.js, apps/core/scenes/bookingDetail/sectorDetails/segments/__tests__/__snapshots__/SegmentMap.test.js.snap, apps/graphql/src/apps/booking/types/outputs/BookingInterface.js, apps/graphql/src/apps/booking/types/outputs/__tests__/BookingInterface.test.js, schema.graphql
Remove segmentLocations from graphql BookingInterface type
see [comment](https://github.com/kiwicom/margarita/pull/389#issuecomment-466920186) for more info
=> MMB: Draw dots as map markers with location name

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/ItineraryCard/__generated__/ItineraryCard.graphql.js, apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetail.js, apps/core/components/ItineraryCard/itineraryDetail/SectorsList.js, apps/core/components/ItineraryCard/itineraryDetail/__generated__/ItineraryDetail.graphql.js, apps/core/components/ItineraryCard/itineraryDetail/__generated__/SectorsList.graphql.js, apps/core/components/sectorDetail/SectorDetail.js, apps/core/components/sectorDetail/__generated__/SectorDetail.graphql.js, apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/bookingDetail/sectorDetails/SectorsListMulticity.js, apps/core/scenes/bookingDetail/sectorDetails/SectorsListOneWay.js, apps/core/scenes/bookingDetail/sectorDetails/SectorsListReturn.js, apps/core/scenes/bookingDetail/sectorDetails/__generated__/SectorsListMulticity.graphql.js, apps/core/scenes/bookingDetail/sectorDetails/__generated__/SectorsListOneWay.graphql.js, apps/core/scenes/bookingDetail/sectorDetails/__generated__/SectorsListReturn.graphql.js, apps/core/scenes/bookingDetail/sectorDetails/segments/SegmentContainer.js, apps/core/scenes/bookingDetail/sectorDetails/segments/__generated__/SegmentContainer.graphql.js, apps/core/scenes/bookingDetail/sectorDetails/segments/__generated__/SegmentMap.graphql.js, apps/core/scenes/results/__generated__/ResultsQuery.graphql.js
Summary: Added Sector details rendering to `ItineraryDetail` and `BookingDetail`.
Note: This PR contains only initial structure and proper `SectorDetail` content will be added separately to keep sane PR size.
=> Feat: SectorDetail initial structure

apps/core/components/ItineraryCard/RenderTripSectorItem.js, apps/core/components/sectorDetail/SectorDetail.js, apps/core/components/sectorDetail/SectorHeader.js, apps/core/components/sectorDetail/SectorStopoverDuration.js, apps/core/components/sectorDetail/__generated__/SectorDetail.graphql.js, apps/core/components/sectorDetail/__generated__/SectorHeader.graphql.js, apps/core/components/sectorDetail/__generated__/SectorStopoverDuration.graphql.js, apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/bookingDetail/sectorDetails/segments/__generated__/SegmentMap.graphql.js, apps/core/scenes/results/__generated__/ResultsQuery.graphql.js, packages/components/index.js, packages/components/package.json, packages/components/src/stopoverDuration/StopoverDuration.js, packages/components/src/stopoverDuration/__tests__/StopoverDuration.test.js, packages/components/src/stopoverDuration/__tests__/__snapshots__/StopoverDuration.test.js.snap
Summary: Added `SectorStopoverDuration` and `SectorHeader` component. 
Updated `StopoverDuration` component to make it reusable and moved it to `@kiwicom/margarita-components`.
=> Feat: Added Header and Stopover to SectorDetail

apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetail.js, apps/core/components/ItineraryCard/itineraryDetail/__generated__/ItineraryDetail.graphql.js, apps/core/scenes/results/__generated__/ResultsQuery.graphql.js, apps/graphql/src/apps/itinerary/Itinerary.js, apps/graphql/src/apps/itinerary/dataloaders/Itineraries.js, apps/graphql/src/apps/itinerary/types/outputs/Itinerary.js, schema.graphql
Summary: Added bookingToken to Itinerary type. And implemented it for redirect from `/results` to `/result-detail`.
It will be required for Booking API calls ( related to #114 )
=> Feat: Added bookingToken to Itinerary

apps/core/scenes/resultDetail/ResultDetail.js, packages/components/package.json, packages/components/src/ExtendedTouchable.js, packages/components/src/TouchableWithoutFeedback.js, packages/components/src/passengerCard/PassengerCard.js, packages/components/src/passengerCard/__tests__/__snapshots__/PassengerCard.test.js.snap
- Add PassengerCard to ResultDetail
- Implement Card from `universal-components` in PassengerCard
- Add ExtendedTouchable component for bigger touchable areas in small elements
- Add edit icon to PlaceCard
=> Add PassengerCard to ResultDetail

packages/components/src/duration/Duration.js
Summary: To make component more reusable. Required for segment details.
=> Feat: Added iconName prop to Duration component

apps/landingPage/src/components/Demo.js, apps/landingPage/src/components/Footer.js, apps/landingPage/src/components/GetStartedInfo.js, apps/landingPage/src/components/Header.js, apps/landingPage/src/components/Headline.js, apps/landingPage/src/components/Info.js, apps/landingPage/src/components/Playground.js
Summary:
+ refactor media queries
+ fix some style inconsistencies with design
=> Refactor css to mobile-first approach in LandingPage

packages/components/src/timelineTransportDetail/TimelineTransportDetail.js, packages/components/src/timelineTransportDetail/components/CardHeader.js
Summary: Replaced duration text with Duration component. So we don't need to repeat duration formatting function implemented directly inside Duration component.
=> Feat: Updated TimelineTransportDetail duration text implementation

apps/core/components/sectorDetail/LayoverInfo.js, apps/core/components/sectorDetail/SectorDetail.js, apps/core/components/sectorDetail/__generated__/SectorDetail.graphql.js, apps/core/components/sectorDetail/segment/Segment.js, apps/core/components/sectorDetail/segment/SegmentConstants.js, apps/core/components/sectorDetail/segment/SegmentStopInfo.js, apps/core/components/sectorDetail/segment/SegmentStopInfoRow.js, apps/core/components/sectorDetail/segment/__generated__/Segment.graphql.js, apps/core/components/sectorDetail/segment/__generated__/SegmentStopInfo.graphql.js, apps/core/scenes/bookingDetail/__generated__/BookingDetailQuery.graphql.js, apps/core/scenes/results/__generated__/ResultsQuery.graphql.js
Summary: Added Segments and Layover info.
=> Feat: Added Segments info to SectorDetail

apps/core/scenes/resultDetail/ResultDetail.js, apps/mobile/src/navigation/SearchStack.js, packages/components/index.js, packages/components/src/passengerCard/PassengerCard.js, packages/components/src/passengerCard/PassengerCardTypes.js, packages/components/src/passengerCard/__tests__/__snapshots__/PassengerCard.test.js.snap, packages/components/src/passengerCards/PassengerCards.js
**What is new:**
- Add component for list of the `PassengerCard`s (called `PassengerCards`)
- Add button for adding new passenger (`Button` should be rounded, it will be updated in some next PR)
- Click on `PassengerCard` edit button returns `ID`
- Some refactoring of `PassengerCard`
=> Create passenger cards

apps/core/index.js, apps/core/scenes/passengerForm/PassengerForm.js, apps/core/scenes/resultDetail/ResultDetail.js, apps/mobile/src/navigation/SearchStack.js, apps/mobile/src/screens/PassengerFormScreen.js, apps/mobile/src/screens/index.js, apps/web/pages/passenger-form.js, packages/navigation/config/routes.js
Summary: Added empty `PassangerForm` screen to structure.
Made edit button leading to form active inside `ResultDetail`.
Related to #121
=> Feat: Added empty PassengerForm screen

apps/graphql/src/services/fetch/Fetch.js, apps/graphql/src/services/fetch/ProxiedError.js, apps/graphql/src/services/fetch/__tests__/ProxiedError.test.js
Error: "Not recognized location: `prague_czk`" wrong API call
before 
now
=> GraphQL: add custom error

apps/landingPage/next.config.js
Otherwise, https://kiwicom.github.io/margarita/ is not displaying pictures.
=> Fix: Assets prefix for landing page

apps/core/scenes/resultDetail/ResultDetail.js, packages/components/index.js, packages/components/src/contactDetailsForm/ContactDetailsForm.js, packages/components/src/headerWithIcon/HeaderWithIcon.js, packages/components/src/passengerCards/PassengerCards.js
=> Add contact details form 

.circleci/config.yml, apps/documentation/siteConfig.js
https://kiwicom.github.io/margarita/docs/
=> Chore: Deploying documentation to gh pages

apps/core/scenes/bookingDetail/BookingDetailWrapper.js, apps/mobile/src/screens/BookingDetailScreen.js, apps/mobile/src/screens/FlightServicesScreen.js, apps/mobile/src/screens/ManageHelpScreen.js, apps/mobile/src/screens/ManageOtherScreen.js, apps/mobile/src/screens/PassengerDetailScreen.js, apps/mobile/src/screens/ShareBookingScreen.js, apps/mobile/src/screens/TicketsScreen.js, apps/mobile/src/screens/TimelineScreen.js, apps/mobile/src/screens/TripServicesScreen.js, packages/components/src/searchParamsSummary/SearchParamsSummary.js, packages/config/index.js
- `Loader` shouldn't be placed inside of the `ScrollView`, that was the main problem
- I also removed `MMB_BACKGROUND_COLOR`. It wasn't real color in the app. Actually I think it's there because it's the color of the background in Figma's artboard and there is no possibility how to pick real color from screen background. I had to take a screenshot from Figma, open it in Photoshop and pick the color (quite shitty, I know, but it works 😄)
Closes #490
=> Fix wrong alignment of loader in BookingDetails

apps/landingPage/components/Headline/ButtonInfo.js, apps/landingPage/components/Headline/GetStartedInfo.js, apps/landingPage/components/Headline/Subtitle.js, apps/landingPage/components/Headline/TextHeadline.js, apps/landingPage/components/Headline/index.js, apps/landingPage/components/Info/ButtonLink.js, apps/landingPage/components/Info/ResponsiveText.js, apps/landingPage/components/Info/index.js
Summary: remove HOC `withWindowSize` and instead of that use media queries
Closes #422
=> Fix: remove window dependent styles

.circleci/config.yml, .flowconfig, apps/mobile/package.json, yarn.lock
Example logs of build
https://circleci.com/gh/kiwicom/margarita/5935
=> Chore: Auto-deploy apps/mobile to Expo

apps/web/package.json, packages/universal-components/package.json, yarn.lock
- Bump react-native-web to 0.10.1 v
- Bump babel-plugin-react-native-web to 0.10.1 v
close #486
=> Chore:  Bump react-native-web and babel-plugin-react-native-web

.flowconfig, apps/core/components/ItineraryCard/FlightTimes.js, apps/core/components/ItineraryCard/TimelineArrow.js, apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetail.js, apps/core/components/priceSummary/PriceSummary.js, apps/core/components/sectorDetail/LayoverInfo.js, apps/core/components/sectorDetail/SectorHeader.js, apps/core/components/sectorDetail/segment/SegmentStopInfoRow.js, apps/core/scenes/bookingDetail/menuGroups/Passengers/Passenger.js, apps/core/scenes/search/Placepickers.js, packages/components/src/alert/AlertContext.js, packages/components/src/contactDetailsForm/ContactDetailsForm.js, packages/components/src/headerWithIcon/HeaderWithIcon.js, packages/components/src/illustration/Illustration.js, packages/components/src/modal/Modal.js, packages/components/src/modal/__tests__/__snapshots__/Modal.test.js.snap, packages/components/src/searchParamsSummary/SearchParamsSummary.js, packages/components/src/tripInput/TripInput.js, packages/components/src/tripTypeButton/TripTypeButton.js, packages/components/src/tripTypeButton/__tests__/__snapshots__/TripTypeButton.test.js.snap, packages/components/src/visaInfo/VisaInfo.js, packages/universal-components/src/Checkbox/CheckboxShared.js, packages/universal-components/src/DatePicker/DatePicker.android.js, packages/universal-components/src/Icon/IconsList.js, packages/universal-components/src/MenuGroup/MenuGroup.js, packages/universal-components/src/MenuGroup/MenuGroupTitle.js, packages/universal-components/src/Picker/Picker.android.js
Summary: Updated `untyped` section in `.flowconfig` (removed unused lines, added few new paths). 
Updated components with flow errors, mostly related to styles.
Closes: #477
=> Fix: Updated .flowconfig and fixed flow errors

apps/core/scenes/search/PlacePicker/PlacePickerContent.js, apps/core/scenes/search/PlacePicker/__tests__/helpers.test.js, apps/core/scenes/search/PlacePicker/helpers.js, apps/core/scenes/search/SearchContext.js
User can delete selected location by backspace key
=> Feat: PlacePicker delete slected location by backspace key

packages/universal-components/src/Picker/Picker.android.js, packages/universal-components/src/Picker/Picker.ios.js, packages/universal-components/src/Picker/Picker.web.js, packages/universal-components/src/Picker/PickerHelpers.js, packages/universal-components/src/Picker/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/PickerButton/PickerButton.js, packages/universal-components/src/PickerButton/PickerButton.stories.js, packages/universal-components/src/PickerButton/PickerButtonWrapper.js, packages/universal-components/src/PickerButton/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/PickerButton/__tests__/index.test.js, packages/universal-components/src/PickerButton/index.js, packages/universal-components/src/index.js
Summary: Separated button component from `Picker` to make it reusable.
Note: This component will be reused for example in new `DateInput`.
=> Feat: Added PickerButton component

apps/core/scenes/passengerDetail/PassengerDetail.js, apps/core/scenes/resultDetail/ResultDetail.js, packages/components/index.js, packages/components/src/passengerCard/PassengerCard.js, packages/components/src/passengerCard/PassengerCardTypes.js, packages/components/src/passengerCard/__tests__/__snapshots__/PassengerCard.test.js.snap, packages/components/src/passengerCards/AddPassengerButton.ios.js, packages/components/src/passengerCards/AddPassengerButton.js, packages/components/src/passengerCards/PassengerCards.js, packages/universal-components/src/MenuGroup/MenuDescription.js, packages/universal-components/src/MenuGroup/MenuItem.js, packages/universal-components/src/MenuGroup/MenuItemWrapper.js, packages/universal-components/src/MenuGroup/__tests__/__snapshots__/MenuItem.android.test.js.snap, packages/universal-components/src/MenuGroup/__tests__/__snapshots__/MenuItem.ios.test.js.snap, packages/universal-components/src/MenuGroup/__tests__/__snapshots__/MenuItem.test.js.snap, packages/universal-components/src/MenuGroup/index.js, packages/universal-components/src/index.js
=> PassengerCards updates

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/scenes/passengerForm/PassengerForm.js, packages/components/index.js, packages/components/src/dateInput/DateInput.js, packages/components/src/dateInput/DateInput.stories.js, packages/universal-components/package.json, packages/universal-components/src/SegmentedButton/SegmentedButton.js
Summary: Added simple `DateInput` component. Which is basically just composite of `PickerButton` and `DatePicker`.
Added passenger related inputs to `PassengerForm` screen.
Closes: #121
=> Feat: Added PassengerForm inputs

apps/core/scenes/search/SearchContext.js
=> Set default departure date to tomorrow

.circleci/config.yml, apps/storybook/package.json
=> Chore: Auto-deploy apps/storybook for universal-components to Expo

packages/universal-components/src/Button/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/FilterButton/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/PickerButton/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/Stepper/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/Touchable/Touchable.js
=> Fix button width on Android

apps/core/scenes/payment/Payment.js, packages/components/index.js, packages/components/src/creditCardPaymentForm/CreditCardPaymentForm.js, packages/components/src/tripTypeSwitch/TripTypeSwitchOption.js, packages/universal-components/src/FormFeedback/FormFeedback.js, packages/universal-components/src/FormLabel/FormLabel.js, packages/universal-components/src/TextInput/TextInput.js, packages/universal-components/src/TextInput/TextInputTypes.js
=> Implement PaymentForm

packages/universal-components/src/TextInput/TextInput.js, packages/universal-components/src/TextInput/TextInput.stories.js, packages/universal-components/src/TextInput/TextInputTypes.js, packages/universal-components/src/TextInput/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/TextInput/__tests__/index.test.js
New prop `inputStyle` to style TextInput component. Closes #555
=> Feat: Expose style prop for TextInput container

apps/core/scenes/payment/Payment.js, apps/core/scenes/resultDetail/ResultDetail.js, packages/components/index.js, packages/components/package.json, packages/components/src/contentContainer/ContentContainer.js, packages/components/src/creditCardPaymentForm/CreditCardPaymentForm.js, packages/universal-components/src/Card/Card.js
Let's make the screens beautiful again 😂
`ContentContainer` component is for keeping content centered on the web. It has also scrolling support.
Closes #561
=> Create ContentContainer for web styling

.eslintignore, apps/core/scenes/passengerForm/BaggageBundles/BagTypes.js, apps/core/scenes/passengerForm/BaggageBundles/BaggageBundle.js, apps/core/scenes/passengerForm/BaggageBundles/BaggageTypeDetail.js, apps/core/scenes/passengerForm/BaggageBundles/Header.js, apps/core/scenes/passengerForm/BaggageBundles/index.js, apps/core/scenes/passengerForm/PassengerForm.js
Summary:
+ Create AddBag Component
Note: 
+ Footer notes not added yet
+ Shadows behave weirdly in IOS. After setting it to the container, its applied to all the components. So this along with android shadow, I ll try to fix later
+ There is one icon missing in universal components for *no personal item*. Am I just not seeing it maybe?
=> Feat: Create AddBaggage component

apps/core/components/ItineraryCard/TripSector.js, apps/core/components/ItineraryCard/TripSectorHelpers.js, apps/core/components/sectorDetail/segment/Segment.js, apps/core/scenes/bookings/DateAndPassengerCount.js, apps/core/scenes/passengerForm/PassengerForm.js, apps/core/scenes/results/Results.js, apps/core/scenes/search/Datepickers.js, apps/core/scenes/search/Search.js, apps/core/scenes/search/SearchConstants.js, apps/core/scenes/search/SearchContext.js, apps/graphql/package.json, apps/graphql/src/apps/booking/Booking.js, apps/graphql/src/apps/booking/dataloaders/Bookings.js, apps/graphql/src/apps/itinerary/__mocks__/itinerariesMock.js, apps/graphql/src/apps/itinerary/dataloaders/Itineraries.js, apps/graphql/src/apps/itinerary/helpers/Itineraries.js, apps/graphql/src/apps/itinerary/helpers/__tests__/Itineraries.test.js, package.json, packages/components/package.json, packages/components/src/dateInput/DateInput.stories.js, packages/components/src/stopoverDuration/StopoverDuration.js, packages/config/index.js, packages/utils/package.json, packages/utils/src/__tests__/formatDate.test.js, packages/utils/src/formatDate.js, yarn.lock
- Updated DateFNS to version 2. (I will need some functions from `date-fns@v2` in new `RangeDatePicker`). Btw there are some very interesting breaking changes 😂 
- Add all date formats to `margarita-config`. It was on many places in the code and it was quite messy.
=> Update to date-fns@v2 and unify dateFormats

apps/core/scenes/search/PlacePicker/NotFound.js, apps/core/scenes/search/PlacePicker/PlacePickerContent.js
=> Feat: NotFound message into the PlacePicker

apps/core/components/ItineraryCard/FlightTimes.js, apps/core/components/sectorDetail/SectorHeader.js, apps/core/components/sectorDetail/segment/SegmentStopInfoRow.js, packages/components/src/tripInput/TripInput.js, packages/design-tokens/src/MargaritaTokens.js, packages/universal-components/src/Badge/Badge.js, packages/universal-components/src/Checkbox/CheckboxText.js, packages/universal-components/src/FilterButton/FilterButton.js, packages/universal-components/src/FormFeedback/FormFeedback.js
Summary: Moved repeating `fontWeightMedium` value to margarita design tokens.
=> Refactor: Added fontWeightMedium to margarita-design-tokens

apps/core/package.json, apps/storybook/package.json, packages/components/package.json, packages/universal-components/.release-it.json, packages/universal-components/package.json, packages/universal-components/src/types/_generated-types/index.js, yarn.lock
=> Chore: @kiwicom/universal-components@0.0.16

apps/graphql/src/Schema.js, apps/graphql/src/apps/itinerary/Itinerary.js, apps/graphql/src/apps/itinerary/dataloaders/Itineraries.js, apps/graphql/src/apps/itinerary/dataloaders/__tests__/Itineraries.test.js, apps/graphql/src/apps/itinerary/queries/SearchReturnItineraries.js, apps/graphql/src/apps/itinerary/queries/__tests__/__fixtures__/itineraries/ItinerariesReturn.graphql, apps/graphql/src/apps/itinerary/queries/__tests__/__snapshots__/ItinerariesQueries.test.js.snap, apps/graphql/src/apps/itinerary/types/inputs/ItinerariesReturnSearchInput.js, apps/graphql/src/apps/itinerary/types/inputs/common/ItineraryCommonInputFields.js, apps/graphql/src/services/graphqlContext/GraphQLContext.js, schema.graphql
Created new `searchReturnItineraries` query. Related to #556
=> Feat: Create new searchReturnItineraries query

docs/guide-tequila-api-key.md
=> Docs: Guide: Get your Tequila API key

apps/core/components/userContext/UserContext.js, apps/core/index.js, apps/core/scenes/profile/Profile.js, apps/core/scenes/profile/SignIn.js, apps/core/scenes/profile/SignOut.js, apps/mobile/App.js, apps/web/pages/_app.js
Summary: Context will hold all user related data. For example contacts, passenger informations, login state or settings like default currency.
Context is used because user data are required on multiple screens (Booking, Profile, Search - if we decide to use currency settings).
=> Feat: Added UserContext

packages/components/index.js, packages/components/src/sortTabs/SortTab.js, packages/components/src/sortTabs/SortTabs.js, packages/components/src/sortTabs/SortTabs.stories.js, packages/components/src/sortTabs/__tests__/__snapshots__/index.test.js.snap, packages/components/src/sortTabs/__tests__/index.test.js, packages/components/src/sortTabs/index.js
Relates to #562. Create SortTabs component for sorting the search based on quality, price or time.
=> Feat: Add SortTabs Component

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/priceSummary/Expander.js, apps/core/components/priceSummary/PriceSummary.js, apps/core/scenes/bookings/Booking.js, apps/core/scenes/passengerForm/baggageBundles/Header.js, apps/core/scenes/payment/Payment.js, apps/core/scenes/search/Placepickers.js, apps/web/components/Navbar.js, apps/web/components/NavbarLink.js, packages/components/index.js, packages/components/src/__tests__/TouchableWithoutFeedback.test.js, packages/components/src/passengerCard/PassengerCard.js, packages/components/src/passengersButton/PassengersButton.js, packages/components/src/passengersButton/PassengersButton.native.js, packages/components/src/passengersButton/__tests__/PassengersButton.test.js, packages/components/src/sortTabs/SortTab.js, packages/components/src/table/TableRow.js, packages/components/src/tripInput/TripInput.js, packages/components/src/tripTypeButton/TripTypeButton.js, packages/components/src/tripTypeButton/__tests__/TripTypeButton.test.js, packages/components/src/tripTypeSwitch/TripTypeSwitchOption.js, packages/universal-components/package.json, packages/universal-components/src/ExtendedTouchable/ExtendedTouchable.js, packages/universal-components/src/ExtendedTouchable/index.js, packages/universal-components/src/TouchableWithoutFeedback/TouchableWithoutFeedback.js, packages/universal-components/src/TouchableWithoutFeedback/index.js, packages/universal-components/src/index.js
Move `TouchableWithoutFeedback` and `ExtendedTouchable` from `margarita-components`to `universal-components`
=> Move touchables to universal-components

packages/universal-components/src/Button/ButtonInner.js, packages/universal-components/src/Button/styles/shared.js
Summary: Simplified conditions for Button padding.
=> Feat: Updated Button padding size rules

apps/core/scenes/results/Results.js, apps/core/scenes/results/ResultsList.js, apps/core/scenes/search/Search.js, apps/core/scenes/search/SearchContext.js, apps/core/scenes/search/SortTabsWrapper.js, apps/mobile/src/screens/ResultsScreen.js, apps/web/pages/results.js, packages/components/src/sortTabs/SortTabs.js, packages/components/src/sortTabs/__tests__/__snapshots__/index.test.js.snap
=> Add SortTabs component on the FE for sorting Search Queries

apps/landingPage/next.config.js
See similar issue https://github.com/kiwicom/margarita/pull/624
=> LandingPage: Fix failing Webpack build

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/ItineraryCard/__generated__/ItineraryCard_data.graphql.js, apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetail.js, apps/core/components/ItineraryCard/itineraryDetail/SectorsList.js, apps/core/components/ItineraryCard/itineraryDetail/__generated__/ItineraryDetail_data.graphql.js, apps/core/components/ItineraryCard/itineraryDetail/__generated__/SectorsList_data.graphql.js, apps/core/scenes/results/ResultsList.js, apps/core/scenes/results/__generated__/OneWayResultsQuery.graphql.js, apps/core/scenes/results/__generated__/ResultsList_data.graphql.js, apps/core/scenes/results/__generated__/ReturnResultsQuery.graphql.js, apps/graphql/src/Schema.js, apps/graphql/src/apps/itinerary/Itinerary.js, apps/graphql/src/apps/itinerary/helpers/queryVariables.js, apps/graphql/src/apps/itinerary/queries/SearchOneWayItineraries.js, apps/graphql/src/apps/itinerary/queries/SearchReturnItineraries.js, apps/graphql/src/apps/itinerary/queries/__tests__/__snapshots__/ItinerariesQueries.test.js.snap, apps/graphql/src/apps/itinerary/types/outputs/ItineraryConnection.js, apps/graphql/src/apps/itinerary/types/outputs/ItineraryInterface.js, apps/graphql/src/apps/itinerary/types/outputs/ItineraryOneWay.js, apps/graphql/src/apps/itinerary/types/outputs/ItineraryReturn.js, schema.graphql
=> Graphql: Make itinerary return type an interface

apps/graphql/src/apps/itinerary/Itinerary.js, apps/graphql/src/apps/itinerary/dataloaders/Itineraries.js, apps/graphql/src/apps/itinerary/dataloaders/Itinerary.js, apps/graphql/src/apps/itinerary/helpers/Itineraries.js, apps/graphql/src/apps/itinerary/helpers/Itinerary.js, apps/graphql/src/apps/itinerary/queries/__tests__/__fixtures__/checkItinerary/CheckItinerary.graphql, apps/graphql/src/apps/itinerary/queries/__tests__/__snapshots__/CheckItineraryQueries.test.js.snap
Summary: 
- Mapped remaining Itinerary data for CheckItinerary.
- Extracted `getItineraryDeparture` and `getItineraryArrival` into `helpers/Itineraries` to make it reusable.
=> Feat: CheckItinerary data mapping

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/ItineraryCard/TripSectorOneWay.js, apps/core/components/ItineraryCard/TripSectorReturn.js, apps/core/components/ItineraryCard/__generated__/ItineraryCard_data.graphql.js, apps/core/components/ItineraryCard/__generated__/TripSectorOneWay_itinerary.graphql.js, apps/core/components/ItineraryCard/__generated__/TripSectorReturn_itinerary.graphql.js, apps/core/components/ItineraryCard/itineraryDetail/ItineraryDetail.js, apps/core/scenes/results/__generated__/OneWayResultsQuery.graphql.js, apps/core/scenes/results/__generated__/ReturnResultsQuery.graphql.js, packages/components/index.js, packages/components/src/itineraryTypeRenderer/ItineraryTypeRenderer.js, packages/components/src/itineraryTypeRenderer/__tests__/ItineraryTypeRenderer.test.js
Add ItineraryTripType renderer component
=> Add trip sector one way and return

packages/universal-components/src/Button/Button.native.js, packages/universal-components/src/Button/Button.stories.js, packages/universal-components/src/Button/Button.web.js, packages/universal-components/src/Button/ButtonInner.js, packages/universal-components/src/Button/ButtonTypes.js, packages/universal-components/src/Button/GenericButtonWrapper.js, packages/universal-components/src/Button/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/Button/__tests__/index.test.js, packages/universal-components/src/Loader/Loader.js
By passing `isLoading` prop Buttons state changes to loading.
Also added `color` prop in Loader component as it is required in design
closes #635
=> Add loading state to Button component

packages/config/index.js
MMB list and detail was  showing date like 020 11/28.
Fixed now to show Wed 11/28
=> MMB: Fix broken date format

packages/universal-components/src/Button/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/Checkbox/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/FilterButton/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/Icon/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/PickerButton/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/Rating/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/Text/Text.js, packages/universal-components/src/TextInput/__tests__/__snapshots__/index.test.js.snap
This is important so that the consumer is able to overwrite defalt props.
=> Fix: Set passed style prop last in text component

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/scenes/resultDetail/__generated__/ResultDetailInnerQuery.graphql.js, apps/core/scenes/resultDetail/__generated__/ResultDetailQuery.graphql.js, apps/core/scenes/resultDetail/resultDetailContent/ResultDetailContent.js, apps/core/scenes/resultDetail/resultDetailContent/__generated__/ResultDetailContent_data.graphql.js, packages/utils/index.js, packages/utils/src/CurrencyFormatter/CurrencyFormatter.js
Summary: 
- Added real itinerary price to `ResultDetailContent` summary.
- Updated `CurrencyFormatter` to return message instead incorrect value in case when value or currency is not specified.
=> Feat: Added real price to ResultDetail

apps/core/scenes/bookingDetail/menuGroups/Passengers/__generated__/Passenger_data.graphql.js, apps/graphql/src/Schema.js, apps/graphql/src/apps/booking/Booking.js, apps/graphql/src/apps/booking/dataloaders/SaveBooking.js, apps/graphql/src/apps/booking/dataloaders/__tests__/SaveBooking.test.js, apps/graphql/src/apps/booking/queries/SaveBooking.js, apps/graphql/src/apps/booking/types/enums/PassengerTitle.js, apps/graphql/src/apps/booking/types/inputs/HoldBags.js, apps/graphql/src/apps/booking/types/inputs/PassengerInput.js, apps/graphql/src/apps/booking/types/inputs/SaveBookingPayload.js, apps/graphql/src/apps/booking/types/outputs/BookingInterface.js, apps/graphql/src/apps/booking/types/outputs/Passenger.js, apps/graphql/src/apps/booking/types/outputs/SaveBooking.js, apps/graphql/src/server.js, apps/graphql/src/services/graphqlContext/GraphQLContext.js, apps/graphql/src/services/helpers/parseAcceptLanguage.js, schema.graphql
=> Feature: Implement save_booking endpoint from Booking API

apps/graphql/src/Schema.js, apps/graphql/src/apps/booking/Booking.js, apps/graphql/src/apps/booking/dataloaders/ConfirmPayment.js, apps/graphql/src/apps/booking/mutations/ConfirmPayment.js, apps/graphql/src/apps/booking/mutations/SaveBooking.js, apps/graphql/src/apps/booking/mutations/__tests__/__datasets__/confirmPayment.json, apps/graphql/src/apps/booking/mutations/__tests__/__fixtures__/ConfirmPayment.graphql, apps/graphql/src/apps/booking/mutations/__tests__/__snapshots__/mutations.test.js.snap, apps/graphql/src/apps/booking/mutations/__tests__/mutations.test.js, apps/graphql/src/apps/booking/types/inputs/ConfirmPaymentPayload.js, apps/graphql/src/apps/booking/types/outputs/ConfirmPayment.js, apps/graphql/src/services/graphqlContext/GraphQLContext.js, schema.graphql
Implement the `confirm_payment` mutation of Tequila Booking API.(https://tequila.kiwi.com/portal/resources/booking_api).
Relates to #537
=> Feature: confirm_payment GraphQL Mutation for Booking Workflow

apps/landingPage/pages/_document.js, apps/landingPage/pages/index.js
Summary: title was removed due to https://github.com/zeit/next.js/blob/master/errors/no-document-title.md, and global styles are added now as dangerouslySetInnerHTML as in /web
=> LandingPage: move Head to _document.js

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/scenes/resultDetail/ResultDetail.js, apps/core/scenes/results/Results.js, apps/core/scenes/results/ResultsList.js, apps/mobile/src/screens/ResultDetailScreen.js, apps/web/pages/result-detail.js
Summary: Replaced mock values with real params for CheckItinerary query.
Which means that result is matching value from results list.
=> Feat: CheckItinerary params

packages/universal-components/src/RangeDatePicker/AnimatedDayItemArrow.js
On iOS was still some problem with sync, now it should be fine.
(Fixes #639)
=> Fix RangeDatePicker arrow sync on iOS

apps/core/scenes/payment/Payment.js, apps/core/scenes/resultDetail/resultDetailContent/ResultDetailContent.js
Removed promo code buttons from booking summary and payment screen.
Because there is no promo code functionality implemented in Tequila.
=> Refactor: Removed Promo code buttons

apps/core/components/searchForm/SearchForm.js, apps/core/package.json, apps/core/scenes/results/Results.js, apps/web/pages/_app.js, apps/web/pages/index.js, apps/web/pages/results.js
Use Context instead of URL for Results. Relates to #682
=> Enhancement: Use Context instead of URL for Results.

apps/core/components/fromTo/CityName.js, apps/core/components/fromTo/FromTo.js
Fixed `FromTo` arrow centering by `CityName` components style update.
**Before** 
---
**After**
=> Fix: FromTo arrow centering

apps/core/components/searchForm/Datepickers.js, packages/config/index.js, packages/universal-components/package.json, packages/universal-components/src/DesignTokens/DesignTokens.js, packages/universal-components/src/RangeDatePicker/DayNames.js, packages/universal-components/src/RangeDatePicker/DraggableItem.ios.js, packages/universal-components/src/RangeDatePicker/DraggableItem.js, packages/universal-components/src/RangeDatePicker/RangeDatePickerContent.js, packages/universal-components/src/RangeDatePicker/RangeDatePickerTypes.js, packages/universal-components/src/RangeDatePicker/RenderDay.js, packages/universal-components/src/RangeDatePicker/RenderMonth.js, packages/universal-components/src/RangeDatePicker/RenderWeek.js, packages/universal-components/src/RangeDatePicker/index.js, packages/universal-components/src/RangeDatePicker/libs.js, packages/universal-components/src/types/index.js, yarn.lock
- **For now iOS only**. Next platforms will come later, there will be a lot of shared code. It works great on real device, but it's laggy in the simulator.
- There are few optimization issues (it's mentioned with `@TODO` in the code)
- Tests are missing
- There is issue during crossing months (when you cross months and `fingerPosition.y < spaceBetweenMonths + touchBuffer`)
- ~~**Types** - I was unable to find proper types for events from `react-native-gesture-handler` (any idea what it could be?)~~
=> Add gestures to RangeDatePicker

apps/graphql/src/apps/itinerary/helpers/Itineraries.js, apps/graphql/src/apps/itinerary/helpers/Itinerary.js, apps/graphql/src/apps/itinerary/helpers/__tests__/Itineraries.test.js, packages/utils/index.js, packages/utils/src/__tests__/differenceInMinutes.test.js, packages/utils/src/__tests__/fromISO.test.js, packages/utils/src/differenceInMinutes.js, packages/utils/src/fromISO.js
Move differenceInMinutes to utils.
Add fromISO function to utils
closes #569
=> Graphql: Refactor differenceInMinutes function

packages/universal-components/src/RangeDatePicker/RangeDatePickerContent.js, packages/universal-components/src/RangeDatePicker/RangeDatePickerTypes.js, packages/universal-components/src/RangeDatePicker/RenderDay.js, packages/universal-components/src/RangeDatePicker/libs.js
=> Scroll to selected date in RangeDatePicker

.gitignore
Fixes comment https://github.com/kiwicom/margarita/pull/712#issuecomment-487579333
=> Added apps/graphql/.webpack to .gitignore

docs/packages/index.md
=> Docs: Added packages folder description

apps/core/components/ItineraryCard/ItineraryCard.js, apps/web/components/NavbarLink.js, apps/web/components/__tests__/Navbar.test.js, apps/web/components/__tests__/NavbarLink.test.js, packages/components/src/sortTabs/SortTab.js, packages/components/src/sortTabs/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/Checkbox/CheckboxShared.js, packages/universal-components/src/DatePicker/DatePickerDayTile.js
=> Feat: Replace Hoverable with new withHover HOC

apps/core/scenes/results/ResultsList.js, packages/components/src/sortTabs/SortTab.js, packages/components/src/sortTabs/SortTabs.js, packages/components/src/sortTabs/__tests__/__snapshots__/index.test.js.snap, packages/universal-components/src/WithHover/withHover.js
=> Feature: Add SortTabs design for mobile

packages/components/src/text/Text.js, packages/components/src/tripInput/TripInput.js, packages/components/src/tripInput/__tests__/__snapshots__/TripInput.test.js.snap, packages/universal-components/src/Text/Text.js, packages/universal-components/src/Text/TextTypes.js
=> Fix: Text is now truncated on datepickers (only one line)

packages/universal-components/src/RangeDatePicker/RenderDay.js
=> Fix Firefox RangeDatePicker styling bug

packages/universal-components/package.json, packages/universal-components/src/RangeDatePicker/DraggableItem.android.js, packages/universal-components/src/RangeDatePicker/DraggableItem.ios.js, packages/universal-components/src/RangeDatePicker/DraggableItem.web.js, packages/universal-components/src/RangeDatePicker/RenderDay.js, yarn.lock
=> Add gestures to RangeDatePicker (web)

docs/folder-structure.md
=> Docs: Added root folders description

packages/components/src/sortTabs/SortTab.js, packages/components/src/sortTabs/SortTabs.js, packages/components/src/sortTabs/__tests__/__snapshots__/index.test.js.snap, packages/components/src/sortTabs/__tests__/index.test.js
The new SortTabs with the mobile design is also applied to the mobile resolution of the web version. Closes #740 .
=> Feature: Put new mobile SortTabs design on web with mobile resolution

apps/core/components/searchForm/SearchForm.js, apps/core/scenes/results/Results.js, apps/core/scenes/results/__generated__/OneWayResultsQuery.graphql.js, apps/core/scenes/results/__generated__/ReturnResultsQuery.graphql.js, apps/core/scenes/search/Search.js, apps/core/scenes/search/SearchContext.js, apps/graphql/src/apps/itinerary/Itinerary.js, apps/graphql/src/apps/itinerary/dataloaders/Itineraries.js, apps/graphql/src/apps/itinerary/dataloaders/__tests__/Itineraries.test.js, apps/graphql/src/apps/itinerary/queries/__tests__/__fixtures__/itineraries/ItinerariesReturn.graphql, apps/graphql/src/apps/itinerary/queries/__tests__/__snapshots__/ItinerariesQueries.test.js.snap, apps/graphql/src/apps/itinerary/types/inputs/common/ItineraryCommonSearchInputFields.js, packages/config/index.js, schema.graphql
Added limit parameter on search with a value of `50`. Closes #746
=> Add limit parameter on Search

apps/core/components/searchForm/DatePicker.js, packages/universal-components/src/RangeDatePicker/RangeDatePicker.js, packages/universal-components/src/RangeDatePicker/RangeDatePickerTypes.js, packages/universal-components/src/RangeDatePicker/components/ControlContainer.js, packages/universal-components/src/RangeDatePicker/components/ControlContainerItem.js
=> Add ControlContainer to RangeDatePicker

apps/graphql/src/apps/itinerary/types/inputs/common/ItineraryCommonSearchInputFields.js, schema.graphql
Serverless deployment did not work last time changes were done to the GraphQL server... test to see if that was a one time thing.
Error was: https://github.com/serverless/serverless/issues/3146
=> Test: Minimum change to GraphQL to test if serverless deployment works

.circleci/config.yml, apps/graphql/package.json, apps/graphql/serverless.yml, yarn.lock
=> Revert "Chore: Get rid of serverless-dotenv-plugin"

apps/graphql/package.json, apps/graphql/serverless.yml, yarn.lock
=> Chore: Add serverless-content-encoding for enabling compression on production

apps/graphql/src/server.js
Adds threshold to the `compression` middleware
=> Chore: Add threshold to the compression middleware to compress small payloads

apps/landingPage/containers/LandingPage.js
Override Roboto in ThemeProvider
=> Use CircularPro in landingPage

apps/core/components/passengerForm/PassengerForm.js, apps/core/components/passengerForm/baggageBundles/BaggageBundle.js, apps/core/components/passengerForm/baggageBundles/BaggageBundles.js, apps/core/index.js, apps/core/scenes/passengerDetail/PassengerDetail.js, apps/core/scenes/resultDetail/resultDetailContent/ResultDetailPassenger.js, packages/components/package.json, packages/components/src/alert/Alert.js, packages/components/src/modal/Modal.js, packages/components/src/modal/__tests__/__snapshots__/Modal.test.js.snap, packages/components/src/passengerCard/PassengerCard.js, packages/components/src/passengerCard/PassengerCardTypes.js, packages/components/src/passengerCard/__tests__/PassengerCard.test.js, packages/components/src/passengerCard/__tests__/__snapshots__/PassengerCard.test.js.snap, packages/components/src/passengerCards/PassengerCards.js
Adding and deleting Passengers is now possible. Relates to #771  
*Validation: Name and ID are mandatory, and the ID has to be unique*.
=> Feature: Add and Delete passengers from a Booking

apps/landingPage/components/LogoCards.js, apps/landingPage/containers/Header.js
on small & large mobile and Tablet
⬇️
=> Improve landingPage Header responsiveness 

.circleci/config.yml, apps/core/components/userContext/UserContext.js, apps/core/index.js, apps/web/components/Navbar.js, apps/web/components/__tests__/Layout.test.js, apps/web/components/__tests__/Navbar.test.js, apps/web/components/__tests__/__snapshots__/Layout.test.js.snap, apps/web/components/__tests__/__snapshots__/Navbar.test.js.snap
=> Feature: Add Login Status (Icon and name) to the Navbar

apps/core/components/passengerForm/PassengerForm.js, apps/core/scenes/passengerDetail/PassengerDetail.js, apps/core/scenes/resultDetail/resultDetailContent/ResultDetailPassenger.js, packages/components/src/passengerCard/PassengerCard.js, packages/components/src/passengerCard/PassengerCardTypes.js, packages/components/src/passengerCard/__tests__/__snapshots__/PassengerCard.test.js.snap
=> Feature: Implement edit passenger feature

apps/landingPage/components/LogoCards.js, apps/landingPage/containers/Header.js
Add custom media query ${defaultTokens.widthBreakpointLargeDesktop + 100}px as the issue was only within that 100px gap
=> Fix responsiveness issue in Header and change font-weight in LogoCard

apps/core/components/bookingContext/BookingContext.js, apps/core/components/passengerForm/PassengerForm.js, apps/core/index.js, apps/core/scenes/resultDetail/resultDetailContent/ResultDetailContent.js, apps/core/scenes/resultDetail/resultDetailContent/ResultDetailPassenger.js, apps/mobile/App.js, apps/web/pages/_app.js, packages/components/index.js, packages/components/src/passengerCard/PassengerCard.js, packages/components/src/passengerCard/PassengerCardTypes.js, packages/components/src/passengerCards/PassengerCards.js
Also,  on booking flow, if no passengers available, do not let the user to the payment stage. Closes  #794
=> Feature: Add booking context / Payment screen passenger number validation

package.json, yarn.lock
"jest": from 24.3.1 to 24.8.0
"jest-expo": from 32.0.0 to 32.0.1
=> Chore: update jest and jest-expo

apps/landingPage/components/FloatedPhone.js, apps/landingPage/containers/Features.js
=> Fix: Landing page Phone not there when refreshing wrong place anymore

apps/core/components/searchForm/DatePicker.js, apps/core/components/searchForm/DatePickerTypes.js, apps/core/components/searchForm/Datepickers.js, apps/core/components/searchForm/SearchForm.js, apps/core/contexts/searchContext/SearchContext.js, apps/core/scenes/results/Results.js, apps/core/scenes/results/__generated__/ReturnResultsQuery.graphql.js, apps/core/scenes/search/Search.js, apps/graphql/src/apps/common/types/inputs/NightsInDestination.js, apps/graphql/src/apps/itinerary/Itinerary.js, apps/graphql/src/apps/itinerary/dataloaders/Itineraries.js, apps/graphql/src/apps/itinerary/types/inputs/ItinerariesReturnSearchInput.js, apps/mobile/src/screens/ResultsScreen.js, packages/config/index.js, packages/universal-components/src/RangeDatePicker/NightsInDestination.js, packages/universal-components/src/RangeDatePicker/RangeDatePicker.js, packages/universal-components/src/RangeDatePicker/RangeDatePickerContent.js, packages/universal-components/src/RangeDatePicker/RangeDatePickerTypes.js, packages/universal-components/src/RangeDatePicker/components/ControlContainer.js, packages/universal-components/src/RangeDatePicker/components/ControlContainerItem.js, schema.graphql
=> Add nightsInDestination to RangeDatePicker

apps/core/contexts/bookingContext/BookingContext.js, apps/core/scenes/resultDetail/ResultDetail.js, apps/core/scenes/resultDetail/ResultDetailInner.js
This is the first PR of little refactoring `checkItinerrary` flow.
1. set up the search and booking context state from URL
2. first call of the `checkItinerrary` happens in the `ResultDetail` component, then refech take input parameter from the context
=> Check itinerary/refactor token to booking context

packages/universal-components/src/RangeDatePicker/RangeDatePicker.stories.js
=> Add storybook to RangeDatePicker

apps/core/components/InformationSection/InformationSection.js, apps/core/index.js, apps/core/scenes/bookingCompleted/BookingCompleted.js, apps/core/scenes/payment/Payment.js, apps/mobile/src/navigation/SearchStack.js, apps/mobile/src/screens/BookingCompletedScreen.js, apps/mobile/src/screens/index.js, apps/web/pages/booking-completed.js, packages/navigation/config/routes.js
=> Feature: Thank you page on booking complete

docs/packages/universal-components/contributing.md
I've added case in troubleshooting, when adb has permission issues.
=> Docs: Add troubleshooting

README.md, apps/mobile/app.json
=> Docs: Add description to Expo app

apps/documentation/siteConfig.js
=> Add Google analytics to docs

apps/core/components/ItineraryCard/ItineraryCard.js, apps/core/components/ItineraryCard/ItineraryCardWrapper.native.js, apps/core/components/ItineraryCard/ItineraryCardWrapper.web.js, apps/core/components/ItineraryCard/__tests__/__snapshots__/ItineraryCard.test.js.snap, packages/components/index.js, packages/components/src/passengerInfoItineraryCard/PassengerInfoItineraryCard.js, packages/components/src/passengerInfoItineraryCard/__tests__/PassengerInfoItineraryCard.test.js, packages/components/src/passengerInfoItineraryCard/__tests__/__snapshots__/PassengerInfoItineraryCard.test.js.snap
=> Feature: Add passenger count information on itinerary card

docs/apps/mobile/index.md
Add documentation for mobile application
=> Docs: Add documentation for Mobile App

docs/apps/web/index.md
Added documentation for the Web application. This closes #856
=> Docs: Add documentation for Web app

docs/packages/margarita-components/index.md
Not much to explain there, just getting rid of all the stubs :)
=> Docs: Add docs for Margarita Components

apps/core/components/passengerForm/PassengerForm.js, apps/core/scenes/resultDetail/resultDetailContent/ResultDetailPassenger.js, packages/components/src/dateInput/DateInput.js
=> Add date validation

package.json, packages/universal-components/src/RangeDatePicker/RangeDatePickerContent.js, packages/universal-components/src/RangeDatePicker/RangeDatePickerTypes.js, packages/universal-components/src/RangeDatePicker/components/RenderDay.js, packages/universal-components/src/RangeDatePicker/components/RenderMonth.js, packages/universal-components/src/RangeDatePicker/components/RenderWeek.js, packages/universal-components/src/RangeDatePicker/libs.js, yarn.lock
=> Improve date boundaries in RangeDatePicker

packages/universal-components/src/RangeDatePicker/components/DraggableItem.web.js, packages/universal-components/src/RangeDatePicker/components/RenderDay.js
=> Fix RangeDatePicker scrolling on web version in iOS 

apps/core/scenes/results/Results.js
Closes #900 
Also solves mobile issue when oneWay wasnt reflected in UI #897
=> Get tripType from context in Results.js

apps/core/components/searchForm/PlacePicker/PlacePickerContent.js, apps/core/scenes/results/Results.js, apps/core/scenes/search/SortTabsWrapper.js, packages/components/src/sortTabs/SortTab.js, packages/components/src/sortTabs/SortTabs.js, packages/components/src/sortTabs/__tests__/__snapshots__/index.test.js.snap, packages/relay/src/QueryRenderer.js, packages/universal-components/src/OptionPicker/OptionPicker.js, packages/universal-components/src/OptionPicker/__tests__/__snapshots__/OptionPicker.test.js.snap, packages/universal-components/src/TagsInput/TagsInput.js
Closes #882 
**Sorting**
**PlacePicker loader and padding**
=> Update UX of search and results

packages/universal-components/src/ModalButtons/ModalButtons.js, packages/universal-components/src/ModalButtons/index.js, packages/universal-components/src/RangeDatePicker/RangeDatePicker.js, packages/universal-components/src/RangeDatePicker/RangeDatePickerTypes.js, packages/universal-components/src/TagsInput/components/TagsContainer.js, packages/universal-components/src/index.js
- `ModalButtons` - Preparation for UX changes in PlacePicker
- Cleaner way how to define default props in RangeDatePicker
=> Add ModalButtons

apps/core/components/searchForm/PlacePicker/PlacePickerContent.js, packages/components/src/modal/Modal.js, packages/universal-components/src/ModalButtons/ModalButtons.js, packages/universal-components/src/OptionPicker/OptionPicker.js, packages/universal-components/src/OptionPicker/__tests__/__snapshots__/OptionPicker.test.js.snap, packages/universal-components/src/TagsInput/TagsInput.js, packages/universal-components/src/TagsInput/components/TagsContainer.js
Search context is changed after click on confirm button,  not all the time
=> Add component state to PlacePicker

apps/core/components/passengerForm/PassengerForm.js, packages/components/index.js, packages/components/src/dateInput/DateInput.ios.js, packages/components/src/dateInput/DateInput.js, packages/components/src/dateInput/index.js
Also refactored PassengerForm so the componentDidUpdated is not needed anymore as DateInput.js would lift state once date composed (not on button click as before).
=> Add ios date input picker

apps/core/scenes/payment/Payment.js, packages/components/index.js, packages/components/src/notification/Notification.js
=> Feat: add a warning to the payment

apps/core/components/searchForm/PlacePicker/PlacePickerContent.js, packages/components/src/modal/Modal.js, packages/universal-components/src/OptionPicker/OptionPicker.js, packages/universal-components/src/OptionPicker/__tests__/OptionPicker.test.js, packages/universal-components/src/OptionPicker/__tests__/__snapshots__/OptionPicker.test.js.snap, packages/universal-components/src/OptionPicker/components/Option.js, packages/universal-components/src/OptionPicker/components/OptionList.js, packages/universal-components/src/RowOption/RowOption.js, packages/universal-components/src/TagsInput/TagsInput.js, packages/universal-components/src/TagsInput/components/DeleteButton.js, packages/universal-components/src/TagsInput/components/InputField.js, packages/universal-components/src/TagsInput/components/Tag.js, packages/universal-components/src/TagsInput/components/TagsContainer.js
=> Improve UX of PlacePicker

apps/core/components/searchForm/PlacePicker/PlacePickerRenderer.js, packages/relay/src/QueryRenderer.js
(different text, but design is the same)
Closes #907
=> Add loader text to PlacePicker
